Tests: Add missing tests to mentorship relation
anitab-org/mentorship-backend pull request #1031
Opened 2021-03-04 08:09 UTC by Sanika1999

### Description

Added Test case for MENTOR_ID_SAME_AS_MENTEE_ID

Fixes #990

### Type of Change:

-Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [X] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [] My changes generate no new warnings 
- [X] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been published in downstream modules

2021-03-08 20:46 UTC, devkapilbansal requested changes

2021-03-08 20:46 UTC, devkapilbansal commented on requirements.txt
> +six==1.14.0
Don't upgrade it as it causes some dependency issues

2021-03-08 20:46 UTC, devkapilbansal commented on tests/mentorship_relation/test_dao_creation.py
> +
Why this extra line here?

2021-03-08 20:46 UTC, devkapilbansal commented on tests/mentorship_relation/test_dao_creation.py
> +    #         end_date = datetime.fromtimestamp(data["end_date"]),
From where you are taking `data[end_date]`. data is not yet created and you are trying to access it. :monocle_face:

2021-03-08 20:46 UTC, devkapilbansal commented on tests/mentorship_relation/test_dao_creation.py
> +
Consider removing empty lines when this PR is ready for a review

2021-03-21 20:14 UTC, devkapilbansal commented
@Sanika1999 any progress?

2021-03-22 14:17 UTC, Sanika1999 commented
> @Sanika1999 any progress?

yes iam still working on this, got a bit delayed because of exams

2021-04-11 13:25 UTC, isabelcosta commented
@Sanika1999 are you still interested in working on this?
It's okay, if not. We can make the issue available again

2021-04-18 09:19 UTC, devkapilbansal commented
Closing due to inactivity

2021-04-18 09:19 UTC, closed without merging