Doc: added steps to create and run migratio nscript
anitab-org/mentorship-backend pull request #1038
Opened 2021-03-06 09:27 UTC by nlok5923

### Description

This pr introduces steps in readme file which will enable user to create and run migration script

Fixes #996 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Documentation update

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-03-06 12:08 UTC, nlok5923 commented
@isabelcosta please do provide suggestion to resolve this issue as i am new to the alembic migrations

2021-03-11 06:41 UTC, devkapilbansal requested changes
@nlok5923 I know it is still a draft but consider giving a link to this section in **TOC**

2021-04-02 06:27 UTC, vj-codes commented
@nlok5923 any updates on this?

2021-04-02 06:46 UTC, nlok5923 commented
@vj-codes yes i am working on it as i am quite novice to alembic script so please can you provide any feedback or clue to approach this issue.

2021-05-03 21:07 UTC, mtreacy002 commented
There are 3 different ways on how we deal with db migration. These are:
1. to create initial migration script (when no version exist in the repo)
2. to add a new version of migration script (when contributors make changes to the db models) 
3. to implement a new version (when contributors pull the latest update from upstream that has a newer version of migration script)
@isabelcosta , can you please specify which of the 3 approaches @nlok5923 need to tackle on this PR? As we don't currently have an initial version of migration script, I'm assuming this pr is to address 1 and 2. Please correct me if I'm wrong 😊 .

2021-05-03 21:13 UTC, mtreacy002 requested changes
@nlok5923 . This is a good start. Please check my feedback below.

2021-05-03 21:13 UTC, mtreacy002 commented on README.md
> +flask db migrate
@nlok5923 , please add the version title to the command so that we have a clear log on what each version is changing. See the screenshot below for example. If you don't add the version title it will be just the auto-generated random number which makes it hard to track.
<img width="389" alt="Screen Shot 2021-05-04 at 6 48 47 am" src="https://user-images.githubusercontent.com/29667122/116932114-3729ce00-aca5-11eb-822c-ba02871ff4b4.png">

The flask-migrate doc [here](https://flask-migrate.readthedocs.io/en/latest/) has an example of using the title version in the command for the initial migration.

2021-05-03 21:13 UTC, mtreacy002 commented on README.md
> +### Create and run db migration script
Depending on @isabelcosta response to [this](https://github.com/anitab-org/mentorship-backend/pull/1038#issuecomment-831534613) post, there might be a slight change here (we need to clearly specify for which purpose the contributor is handling the migration script and address each section accordingly).

2021-05-23 11:13 UTC, epicadk commented
Closing due to inactivity. Thankyou for your contribution @nlok5923

2021-05-23 11:15 UTC, closed without merging