enhanced code of user.py with dict.get()
anitab-org/mentorship-backend pull request #1116
Opened 2021-05-25 09:30 UTC by aakankshaagr

### Description

Fixes #1065 

### Type of Change:

- Code
- Quality Assurance

### How Has This Been Tested?

Tested on my local pc

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-05-25 20:57 UTC, vj-codes commented
@aakankshaagr the build check is failing , can you please look into it ?

2021-05-26 08:33 UTC, aakankshaagr commented
sure @vj-codes !! I looked into tests and found that the test case is failing bcz test is to check " " to be treated as none and I guess it's happening bcz of use of dict.get() as it returns none only when the key is absent. If the key is present it will return whatever value user has given.

![image](https://user-images.githubusercontent.com/71868375/119624518-dd8d6d00-be26-11eb-8775-bdd458052537.png)

Here there is an error related to timestamp. I don't know how to remove this error.

![image](https://user-images.githubusercontent.com/71868375/119624868-36f59c00-be27-11eb-9143-afe5b192619f.png)

So tests are failing bcz there is an error and a test fail.

2021-05-27 13:28 UTC, aakankshaagr commented
![image](https://user-images.githubusercontent.com/71868375/119833926-258ebb80-bf1d-11eb-8f3a-b7c47af4250b.png)
I tried using `dict.get("key",None) or None` to save variable with none if any false values are given as input but still test is failing.

2021-06-09 13:57 UTC, devkapilbansal requested changes
Hi @aakankshaagr thanks for this
There are some more places where this method can be used, like from line 42-47 (mentioned in issue too). Kindly look into the same

2021-06-09 14:56 UTC, aakankshaagr commented
Hi @devkapilbansal thanks for helping me out. I thought earlier that its not needed there but I guess using dict.get() there initializes empty values with None. I missed this point

2021-06-09 14:58 UTC, aakankshaagr commented
I made the changes but still tests are failing

2021-06-09 17:54 UTC, devkapilbansal commented
> I made the changes but still tests are failing

First of all, please update your code with current develop

2021-06-13 12:54 UTC, aakankshaagr commented
@devkapilbansal please check if any changes are required

2021-06-18 18:24 UTC, devkapilbansal requested changes
Hi @aakankshaagr please rebase your branch to current develop. j
Also, there are some minor changes as suggested below :point_down:

2021-06-18 18:24 UTC, devkapilbansal commented on app/api/dao/user.py
>          if "name" in data and data["name"]:
We don't need these if conditions too

2021-06-18 18:24 UTC, devkapilbansal commented on app/api/dao/user.py
>          if "bio" in data:
Same as above similar for above cases as well

2021-06-18 18:24 UTC, devkapilbansal commented on app/api/dao/user.py
> +        new_password = data.get("new_password", None)
None can be removed here as it is the default value returned
```suggestion
        current_password = data.get("current_password")
        new_password = data.get("new_password")
```

2021-06-20 10:54 UTC, closed without merging

2021-06-20 11:04 UTC, devkapilbansal commented
Hi @aakankshaagr why this PR is closed??

2021-06-21 07:20 UTC, aakankshaagr commented
Hi @devkapilbansal earlier my branch wasn't updated with current develop even though I haven't forgotten to do a git pull to update my codebase and here I needed to rebase my branch to current develop. 
To simplify my work I merged all my commits of this issue into one commit and then rebased that commit to the current develop and made some changes to the code.
While trying to push all that changes, I can't find my changes here in this PR so I created a new PR.