Fix error status code and written unittests for Resend Email
anitab-org/mentorship-backend pull request #1123
Opened 2021-06-20 05:33 UTC by harshakhmk

### Description

Fixed status code, error responses for Resend Email endpoint and written unit tests

Fixes # [625](https://github.com/anitab-org/mentorship-backend/issues/625)

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [x] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-06-20 05:37 UTC, harshakhmk commented
@isabelcosta  @vj-codes @devkapilbansal I have raised an MR kindly review it, let me know if there any changes

2021-06-20 06:30 UTC, devkapilbansal requested changes
Hi @harshakhmk I have some minor requests. Please look into the same

2021-06-20 06:30 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +        super(TestResendEmailApi, self).setUp()
Why this is required?

2021-06-20 06:30 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +            name=user1["name"] + "Example",
```suggestion
            name=user1["name"],
```

2021-06-20 06:30 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +        )
If I am not wrong, dictionary unpacking should work
```suggestion
        self.verified_user = UserModel(**user1)
```

2021-06-20 06:30 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +        self.assertEqual(409, actual_response.status_code)
Don't use hard coded values
```suggestion
        self.assertEqual(HTTPStatus.CONFLICT, actual_response.status_code)
```

2021-06-20 06:30 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +        )
If that works fine, we will open an issue to refactor other places too.

2021-06-20 07:14 UTC, harshakhmk commented
@devkapilbansal  updated the code

2021-06-21 12:18 UTC, devkapilbansal requested changes
Great work @harshakhmk 
Just some minor changes required :point_down:

2021-06-21 12:18 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +    def test_error_code_for_resend_email(self):
Use descriptive names
```suggestion
    def test_resend_email_user_already_verified(self):
```

2021-06-21 12:18 UTC, devkapilbansal commented on tests/users/test_api_resend_email.py
> +        self.assertEqual(HTTP_STATUS.CONFLICT, actual_response.status_code)
Please assert the message returned too here

2021-07-03 11:05 UTC, harshakhmk commented
I have updated the commit @devkapilbansal @isabelcosta

2021-07-03 11:20 UTC, devkapilbansal approved these changes
LGTM :+1:

2021-07-03 11:26 UTC, devkapilbansal requested changes
@harshakhmk can you please add some more test cases too here?
I just found that Resend Email wasn't tested before. One case that can be tested is resend mail successfully.

@isabelcosta please approve the workflow run as @harshakhmk is first time contributor.

2021-07-03 18:58 UTC, isabelcosta commented
@devkapilbansal thank you for pinging me for this 🙏🏾

2021-07-15 20:32 UTC, devkapilbansal commented
@harshakhmk tests are failing. Please fix them and update the code.

2021-07-24 13:59 UTC, vj-codes commented
@harshakhmk any updates about this PR?

2022-10-01 09:22 UTC, closed without merging