Change task comment api
anitab-org/mentorship-backend pull request #1126
Opened 2021-06-26 10:40 UTC by RiddhiAthreya

### Description

- The API endpoint /mentorship_relation/{relation_id}/task/{task_id}/comments/  response has been changed to include the details of the users involved in the task comments.
- Swagger UI docs has been changed to reflect the same

The response has been changed to :
` Comments : list of comment objects`
`mentor : dictionary of mentor details`
`mentee : dictionary of mentee details`

Fixes # [1110](https://github.com/anitab-org/mentorship-backend/issues/1110)

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Has been tested in local environment by accessing the endpoint 

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Update Postman API at /docs folder

**Code/Quality Assurance Only**

- [ ] Unit test cases have to be changed to the new response

2021-06-26 11:02 UTC, RiddhiAthreya commented
@epicadk I've made a PR , please let me know if any changes are required

2021-06-27 12:16 UTC, epicadk commented
Also link #685

2021-06-27 12:18 UTC, epicadk commented
If in the future we want to have a mentor groups then I think this would not be easily extendable to that.

2021-06-27 12:40 UTC, RiddhiAthreya commented
@epicadk Oh I see. Then should I include the corresponding user's details in each comment object?

2021-06-29 09:55 UTC, RiddhiAthreya commented
@epicadk I've made the changes in the latest commit. Let me know if any changes are required

2021-07-24 13:51 UTC, vj-codes requested changes
@RiddhiAthreya please resolve the merge conflicts

2025-01-19 00:25 UTC, closed without merging