fix: refactor HTTP error codes for PUT /mentorship_relation/{request_id}/task/{task_id}/comment/{comment_id}
anitab-org/mentorship-backend pull request #1127
Opened 2021-06-27 08:42 UTC by RiddhiAthreya

### Description

Made changes to the HTTP error codes being returned according to what's discussed in the issue. I have also made the appropriate changes in the swagger documentation.

Fixes  #634

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
![Screenshot (172)](https://user-images.githubusercontent.com/54843776/123538133-de306080-d750-11eb-8a35-9fd4fac620db.png)

![Screenshot (173)](https://user-images.githubusercontent.com/54843776/123538136-dffa2400-d750-11eb-8ab2-b7ad0867449b.png)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Update Swagger documentation 

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

2021-06-28 05:36 UTC, vj-codes commented
@RiddhiAthreya the linked issue is a `first timers only` issue, and you have already made your first contribution through #1126. Please check the issue labels while claiming next time :)

2021-07-24 13:50 UTC, vj-codes requested changes
@RiddhiAthreya please resolve the merge conflicts

2021-08-02 19:17 UTC, devkapilbansal requested changes
@RiddhiAthreya I see you remove the changes done for pre-commit. Please revert those changes.

2021-08-02 19:17 UTC, devkapilbansal commented on .flake8
> -    # E501: line too long (> 88 characters)
Why this file is deleted?

This is important for flake8 to work correctly.

2021-08-02 19:17 UTC, devkapilbansal commented on .github/CONTRIBUTING.md
> +* When you are finished with your work, please squash your commits otherwise we will squash them on your PR (this can help us maintain a clear commit history).
There should not be any space at the end. Trim the whitespace please

2021-08-02 19:17 UTC, devkapilbansal commented on .github/CONTRIBUTING.md
> +* In an active repository (not an archived one), choose an open issue from the issue list, claim it in the comments, and a maintainer will assign it to you.
Same as above. Same for similar cases as well

2021-08-02 19:17 UTC, devkapilbansal commented on .isort.cfg
> -[tool.isort]
This should not be deleted too :sweat_smile:

2021-08-02 19:18 UTC, devkapilbansal commented
If you are unsure how this will be done, then feel free to ask :smile:

2021-08-28 18:58 UTC, devkapilbansal commented
@RiddhiAthreya are you working on this?

2021-10-15 00:28 UTC, isabelcosta commented
I will close this PR and unassign due to lack of response.
Thank you for your contribution @RiddhiAthreya so far :)

2021-10-15 00:28 UTC, closed without merging