Enhancement : Require mentor's approval for task completion
anitab-org/mentorship-backend pull request #1130
Opened 2021-07-06 08:24 UTC by RiddhiAthreya

### Description

Task has got new property requires_approval: [bool]. If it's set to True during creation, task becomes "restricted" - i.e only mentor can mark it as done/completed. When mentee tries to mark it as done, he get's 401 Unauthorized.

Fixes #278 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

When a mentee tries to update a task which has `requires_approval `set to True
![Screenshot (190)](https://user-images.githubusercontent.com/54843776/124566973-280bfb80-de61-11eb-8aba-740a0f2cefd0.png)

creating a task with `required_approval `set to True
![Screenshot (191)](https://user-images.githubusercontent.com/54843776/124566980-293d2880-de61-11eb-9b0d-4b1803260303.png)

When mentor tries to update a task which has requires_approval set to True
![Screenshot (192)](https://user-images.githubusercontent.com/54843776/124566982-29d5bf00-de61-11eb-9e89-3fbdd1b89203.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-06 09:09 UTC, epicadk commented
You'll also need to add migrations

2021-07-06 09:57 UTC, RiddhiAthreya commented
@epicadk can you please tell me how to add that?

2021-07-06 13:31 UTC, epicadk commented
> @epicadk can you please tell me how to add that?

I believe @mtreacy002 was going to create a doc for this?

2021-07-08 05:31 UTC, mtreacy002 commented
> You'll also need to add migrations

@epicadk , IMO @RiddhiAthreya doesn't need to write a migration script here since the changes applies to dao object of Task and the logic used inside Task db model. The Task db model itself doesn't get affected with the changes here. I tried running flask db migrate and got the response below.

<img width="720" alt="Screen Shot 2021-07-08 at 3 30 36 pm" src="https://user-images.githubusercontent.com/29667122/124867451-79eb8780-e001-11eb-8bfd-52462cb2a791.png">

Let me know if you have a different view on this 😉

2021-07-08 07:52 UTC, RiddhiAthreya commented
@mtreacy002 true , only the task json object has changed, but the task table remains the same :smiley:

2021-07-25 21:39 UTC, devkapilbansal requested changes
@RiddhiAthreya I see this will work but how the mentor is going to approve the task??

Also, we need some test cases for this too

2021-07-25 21:39 UTC, devkapilbansal commented on app/api/dao/task.py
> +            requires_approval = False
```suggestion
        requires_approval = data.get('requires_approval') or False
```

2021-09-09 08:39 UTC, devkapilbansal commented
@RiddhiAthreya any updates?

2025-01-19 00:25 UTC, closed without merging