style: Add doc strings for UserDao class and its functions
anitab-org/mentorship-backend pull request #156
Opened 2018-12-18 08:21 UTC by Isfaaq

### Description
Added doc string as per requirements of issue #154 

Fixes #154 

### Type of Change:

- Documentation

### How Has This Been Tested?

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x ] I have performed a self-review of my own code or materials
- [x ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

2018-12-29 21:03 UTC, isabelcosta requested changes
@Isfaaq Thank you for sending this PR 🎉 

- Be careful when you write doc strings because you have to understand what the function actually does.
- Try to fix [Codacy warnings](https://app.codacy.com/app/m-murad/mentorship-backend/pullRequest?prid=2767885)
- I left some comments for you to fix. Once you fix those I can approve and merge :)
- After addressing my comments and squashing the commits, fix the commit message to start with `docs:` instead of `style:`

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +    Functions:
Remove this section "Functions". It isn't needed.

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +    """ Class definition for UserDAO.
Do this:
```
"""Data Access Object for User related functionalities.
```

Instead of this:
```
""" Class definition for UserDAO.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +    Provides various functions pertaining to user.
Do this:
```
Provides functions that interact with the User data model, handling create, read, update and delete operations among other util functions.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +        Creates a new user if the current username is not taken. Otherwise returns a message.
Creates a new user if the current username or email is not taken. (...)

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            user_id : The user id of the user being deleted.
```suggestion
            user_id : id of the user being deleted.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +        """Finds a user.
```suggestion
        """Finds a user by id.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            user_id : The user id of the required user.
```suggestion
            user_id: The id of the required user.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            email : The email of the required user.
```suggestion
            email: The email of the required user.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            username : The username of the required user.
```suggestion
            username: The username of the required user.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            list_of_users : List of user ids.
```suggestion
            list_of_users : List of users.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +        Returns a list of users which has been searched by their user_id.
```suggestion
        Returns a list of all users excluding the user which has the user_id.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            user_id : user_id of the user whose details are to be updated.
```suggestion
            user_id : The id of the user that requires an update.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +        Updates the information pertaining to a given user and saves it to the database.
```suggestion
        Updates the information belonging to a given user and saves it to the database.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            message: A message corresponding to the performed action.
```suggestion
            message: A message indicating success or failure of the update action.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            user_id : user_id of the user whose details are to be updated.
```suggestion
            user_id : The id of the user whose password is to be updated.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            message: A message corresponding to the performed action.
```suggestion
            message: A message indicating the success or failure status of this action.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            token : Token which has been emailed.
```suggestion
            token: Token which has been emailed for confirmation.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            message: A message corresponding to the performed action.
```suggestion
            message: A message indicating the success or failure status of this action.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            message: A message containg a description of the action performed.
```suggestion
            message: A message indicating the success or failure status of this action.
```

2018-12-29 21:03 UTC, isabelcosta commented on app/api/dao/user.py
> +            message: A message corresponding to the completed action; success or failure.
```suggestion
            message: A message indicating the success or failure status of this action.
```

2019-01-05 21:57 UTC, isabelcosta commented
@Isfaaq do you want to continue contributing to this PR? If not, I will close this and let other people contribute.

2019-01-09 04:07 UTC, Isfaaq commented
Yes. I am working on it.

2019-01-09 22:12 UTC, isabelcosta requested changes
Left more changes for you @Isfaaq to address. You're almost done ;)

2019-01-09 22:12 UTC, isabelcosta commented on app/api/dao/user.py
> +        Returns a user which has been searched by their id.
This explanation is not needed. You can remove this because the first line explains everything ;)

2019-01-09 22:12 UTC, isabelcosta commented on app/api/dao/user.py
> +        Returns a user which has been searched by their username.
remove this explanation, because the 1º line says everything

2019-01-09 22:12 UTC, isabelcosta commented on app/api/dao/user.py
> +            password: List containing the current and new password and their corresponding values.
you are missing the return part here. This function either returns a user or None, please explain that following the doc string guide.

2019-01-09 22:12 UTC, isabelcosta commented on app/api/dao/user.py
> +        Deletes a user provided the latter exists and deleting them will not cause the number of admins to go below the minimum threshold.
```suggestion
        Deletes a user if this user is not the only admin.
```

2019-01-09 22:12 UTC, isabelcosta commented on app/api/dao/user.py
> +    """ Data Access Object for User related functionalities.
```suggestion
    """Data Access Object for User related functionalities.
```

2019-01-30 23:01 UTC, isabelcosta commented
@Isfaaq are you still working on this? If not i will release this for another contributor, if yes, please do the request changes. There is **no problem** if you don't work on this anymore, anyone else can continue your work, that is Open Source :)

2019-01-31 18:16 UTC, Isfaaq commented
Hello. I am still working on it.

2019-01-31 18:23 UTC, isabelcosta commented
Can you update the issue with the changes changes I requested? @Isfaaq

2019-01-31 18:29 UTC, 0x15F9 commented
Done.

2019-01-31 22:29 UTC, isabelcosta requested changes
@Isfaaq This PR looks good now 🎉 
I just need you to squash your commits into 1 and follow our [Commit Message Style Guideline](https://github.com/systers/mentorship-backend/wiki/Commit-Message-Style-Guide) (using `docs:` instead of `style:`).

2019-02-01 04:17 UTC, Isfaaq commented
Could you point me to the relevant resources on how to squash commits? Thanks/

2019-02-01 19:05 UTC, jaerjaerbin commented
> Could you point me to the relevant resources on how to squash commits? Thanks/

Hi @Isfaaq 
I've been working on a similar issue like this. I had to do some changes and squash commits too, @isabelcosta provided one guide in my PR. I left the link here: https://systers-opensource.slack.com/archives/CAE8QK41L/p1528726928000811 

Hope it helps you!

2019-02-02 07:23 UTC, 0x15F9 commented
Thanks @jaerjaerbin

2019-02-02 11:53 UTC, isabelcosta commented
Thank you @jaerjaerbin for pointing for helpful resources 🎉 
I hope that helps you @Isfaaq :)

2019-02-06 10:03 UTC, Isfaaq commented
@isabelcosta i cannot access the slack workspace provided by @jaerjaerbin

2019-02-06 10:18 UTC, isabelcosta commented
@Isfaaq in the README s contact section you can find the link to join our slack workspace. Can you go there and join please?

2019-02-19 20:25 UTC, isabelcosta commented
I will close this up because of inactivity from the contributor.

2019-02-19 20:25 UTC, closed without merging