docs : added doc strings for AdminDao class and its functions
anitab-org/mentorship-backend pull request #164
Opened 2018-12-29 06:02 UTC by sarnava1

### Description
Added doc strings for AdminDao class and its functions

Fixes #153 

### Type of Change:
**Delete irrelevant options.**

- Quality Assurance
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2018-12-29 06:04 UTC, sarnava1 commented
@isabelcosta I think this PR is now fine. Please review it.

2018-12-29 13:35 UTC, isabelcosta commented
When you create a new PR like this related to another PR or issue relate them in some way to keep track of the history. Please update pr description with a link to the other PR @sarnava1

2018-12-29 14:28 UTC, sarnava1 commented
@isabelcosta done.

2018-12-29 14:28 UTC, sarnava1 commented
Please review @isabelcosta.

2018-12-29 20:27 UTC, isabelcosta requested changes
@sarnava1 Left one change request.

Also the commit message does not have a space between "docs" and ":" so:
Before:
```
docs : added doc strings for AdminDao class and its functions
```

After:
```
docs: added doc strings for AdminDao class and its functions
```

If you get any problem with git or terminal stuff, tell me.
I'll be more than happy to help you :)

2018-12-29 20:27 UTC, isabelcosta commented on app/api/dao/admin.py
> +    """Data Access Object for Admin functionalities."""
Space below this line please.

2018-12-29 20:28 UTC, isabelcosta commented on app/api/dao/admin.py
> +    """Data Access Object for Admin functionalities."""
one line below only

2018-12-30 14:44 UTC, sarnava1 commented
@isabelcosta please review the PR. I will squash the commits if you give the green signal.

2018-12-30 14:47 UTC, isabelcosta submitted a review, later dismissed
Green signal given!

2018-12-30 14:48 UTC, isabelcosta commented
@sarnava1 remember about the comment I made on the commit message. Your 2° commit didn't change

2018-12-30 14:50 UTC, sarnava1 commented
@isabelcosta Actually I could not understand what I should do!! Initially I gave "docs: added ...." and now I gave "docs : added ..." 

Which should I finally give?

2018-12-30 14:51 UTC, isabelcosta commented
First option you mentioned @sarnava1

2018-12-30 14:51 UTC, sarnava1 commented
Ok @isabelcosta

2018-12-30 14:53 UTC, sarnava1 commented
@isabelcosta I am getting this error:

![error_1](https://user-images.githubusercontent.com/25319565/50548333-bee41580-0c70-11e9-8618-fa41a0241f56.png)

2018-12-30 14:56 UTC, isabelcosta commented
@sarnava1 I'm on my phone now, can you share that on slack please. I'm sure someone will help you out!

2018-12-30 14:57 UTC, sarnava1 commented
@isabelcosta sure!

2018-12-30 14:57 UTC, isabelcosta commented
Uh wait. Always check if you can fix Codacy warnings. You have one error pending @sarnava1 fix that please

2018-12-30 14:59 UTC, sarnava1 commented
@isabelcosta the codacy warning is because of the blank line I inserted as you asked me to do. Initially I did not put that blank line because it was giving the codacy errors.

2018-12-30 16:25 UTC, isabelcosta commented
@sarnava1 I verified now that the trailing whitespace problem isn't related to the new line but with the space characters you have in that blank line:

![image](https://user-images.githubusercontent.com/11148726/50549144-5df81580-0c4f-11e9-87b2-cf9bbb63c7ac.png)

highlighted in blue is the trailing whitespace. You can add a blank line without spaces in that line. Do you understand @sarnava1?

2018-12-30 17:38 UTC, sarnava1 commented
Ok @isabelcosta I am trying it out.

2018-12-30 17:56 UTC, sarnava1 commented
@isabelcosta the checks have passed!!

2018-12-30 18:09 UTC, isabelcosta commented
Yey! @sarnava1 you learned something here ;)

2018-12-30 18:10 UTC, isabelcosta commented
Ok so now you can try to squash the commits :)

2018-12-30 18:21 UTC, sarnava1 commented
@isabelcosta I learnt a lot here!! I will try to squash the commits.

2018-12-31 08:39 UTC, sarnava1 commented
@isabelcosta I am getting the same error again!! I have posted it in the slack channel too!

2019-01-03 20:20 UTC, isabelcosta approved these changes
Good job @sarnava1 ! Thank you for your patient :) I'm glad you got to solve your git problem!

2019-01-03 20:21 UTC, merged