Run flake8 checks before tests
anitab-org/mentorship-backend pull request #174
Opened 2019-01-03 14:11 UTC by iulianav

### Description
Add shell script that runs flake8 linter before running unit tests. This will ensure that any new PR follows the PEP8 code standards. It can be run both locally and on Travis.

Fixes #173 

### Type of Change:

- Quality Assurance

### How Has This Been Tested?
Locally it works. Flake8 had to be added to `requirements.txt`. It still has to be tested on Travis, however, the flake8 checks are expected to fail for now and a general refactoring needs to be done in order for the project to abide by PEP8.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] New and existing unit tests pass locally with my changes

Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>

2019-01-03 15:33 UTC, iulianav commented
@isabelcosta for linting errors check Travis on this branch.

2019-02-01 08:57 UTC, ramitsawhney27 requested changes
I read the log and understood why the build fails. If there are any changes that should be done according to flake8, a non zero exit code will return which causes the failure. Can we migrate the tests to pylint instead of flake8 and put a score condition of files needing to have a rating greater than 7 for now?

2019-02-05 23:50 UTC, isabelcosta commented
@iulianav what do you think of @ramitsawhney27 's suggestion, can you do that here?

2019-02-18 03:51 UTC, iulianav commented
@isabelcosta @ramitsawhney27 please note I specified in .pylintrc that TODO warnings and generated members errors for SQLAlchemy(), aka db, should be ignored. When running pylint, i explicitly use the flag `--disable=C0111` which ignores missing docstrings warning as we do not have this at the moment. It can, however, be also specified in .pylintrc.

Throughout the refactoring, instead of ignoring warnings that cannot be fixed at the moment in .pylintrc, I decided to just add in-code comments like `pylint: disable=warning-type` so that people who will wish to do further refactoring in the future are aware of them. What do you think? Thank you!

2019-02-18 08:04 UTC, ramitsawhney27 commented
Seems perfect, can we fix the failing build?

2019-02-18 16:32 UTC, iulianav commented
@ramitsawhney27 on it. I am trying to figure out how to make pylint pass for a score > 7. ALso, i need to refactor a bit more.

2019-02-18 17:18 UTC, iulianav commented
@ramitsawhney27 also, i am not sure it is a good idea to put a condition on the pylint score for *each* file, that would be a bit complicated to do i think. We can have a global condition like the overall score should be > 7 or just fix everything (score 10) and ignore what cannot/should not be fixed. What do you think?

2019-02-18 23:58 UTC, iulianav commented
@ramitsawhney27 @isabelcosta both PRs regarding refactoring are ready. This PR must be merged after the refactoring one in order for it to pass. OR I could just add this work to the other PR and merge everything at once. What do you say?

2019-02-19 07:05 UTC, ramitsawhney27 commented
Either works.

2019-02-19 22:20 UTC, iulianav commented
@ramitsawhney27 then I would say 2 different PRs related to separated concerns so that we can better track the changes in the history of commits if needed?

2019-02-21 20:57 UTC, isabelcosta commented
2 PRs seems good @iulianav ;) I'll wait for the other PR then, before reviewing this one again.
cc @ramitsawhney27

2019-02-21 20:59 UTC, isabelcosta commented
Status: this is blocked by #177

2019-02-21 21:39 UTC, iulianav commented
@isabelcosta thank you!

2020-05-14 18:39 UTC, SanketDG commented
Is this still relevant? IMO we should use something like `flake8/pylint` for linting. Just an autoformatter is not enough,

@iulianav Are you interested in reviving this?

2020-07-25 11:57 UTC, isabelcosta commented
Due to how of this PR being outdated and inactivity I will close this. We can make another PR, using GitHub actions for these checks.
Thank you so much for your work @iulianav with this PR 🙏

2020-07-25 11:57 UTC, closed without merging