docs: added doc strings for TaskDao class and its functions
anitab-org/mentorship-backend pull request #179
Opened 2019-01-21 05:25 UTC by jaerjaerbin

### Description
Added doc strings for TaskDAO class and its functions

Fixes [#166](https://github.com/systers/mentorship-backend/issues/166)

### Type of Change:

- Quality Assurance
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2019-01-21 10:24 UTC, isabelcosta commented
@jaerjaerbin your PR seems fine, @Sys-bot is closing it because the PR template isn't being followed, it can be a "#" missing something you removed that @Sys-bot is expecting. I can only fix this when I get home at night, you can also fix it if you'd like

2019-01-21 20:36 UTC, isabelcosta commented
Just so you know @jaerjaerbin you don't need to actually put the link for the issue on GitHub, if you are in the repository context ;) you can just put `#166` and GitHub will make the link by itself

2019-01-21 20:54 UTC, isabelcosta requested changes
Thank you for sending this pull request @jaerjaerbin !
You did a great job with it. I just left some corrections, to keep it consistent with the rest of the doc strings made for the project.

Can you please do the changes I requested and squash your commits in the end?
Feel free to ask any question if you have any doubt!

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +        Otherwise returns a message.
remove this line, since this will always return a message, and you will indicate its meaning in the `Return:` section

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            user_id: The primary key of user.
```suggestion
            user_id: The id of the user.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            mentorship_relation_id: The primary key of the mentorship relation.
```suggestion
            mentorship_relation_id: The id of the mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            message: A message corresponding to the completed action.
```suggestion
            message: A message indicating if the task creation was successful or not.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            user_id: The primary key of user.
```suggestion
            user_id: The id of the user.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +        Lists all tasks from a mentorship relation for the specified user. Otherwise returns a message.
```suggestion
        Lists all tasks from a mentorship relation for the specified user if the user is involved in a current mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            mentorship_relation_id: The primary key of the mentorship relation.
```suggestion
            mentorship_relation_id: The id of the mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            A list of tasks.
```suggestion
            A list of tasks or an error message.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +        """Removes a specified task from a mentorship relation.
```suggestion
        """Deletes a specified task from a mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +        mentorship relation. Otherwise returns a message.
```suggestion
        mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            user_id: The primary key of user.
```suggestion
            user_id: The id of the user.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            mentorship_relation_id: The primary key of the mentorship relation.
```suggestion
            mentorship_relation_id: The id of the mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            task_id: The primary key of the task.
```suggestion
            task_id: The id of the task.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            message: A message corresponding to the completed action.
```suggestion
            A message indicating if the task was deleted successfully or not.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +        """Sets a task as completed or achieved.
```suggestion
        """Marks a task as completed.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +        mentorship relation to finished task status. Otherwise returns a message.
```suggestion
        mentorship relation to finished task status.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            user_id: The primary key of user.
```suggestion
            user_id: The id of the user.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            mentorship_relation_id: The primary key of the mentorship relation.
```suggestion
            mentorship_relation_id: The id of the mentorship relation.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            task_id: The primary key of the task.
```suggestion
            task_id: The id of the task.
```

2019-01-21 20:54 UTC, isabelcosta commented on app/api/dao/task.py
> +            message: A message corresponding to the completed action.
```suggestion
            A message indicating if the task was set to complete successfully or not.
```

2019-01-21 23:36 UTC, jaerjaerbin commented
Yes, I will do those changes. But I'm kind of new in this subject. So, how should I squash my commits in the end of this PR. Thanks for your help by advance.

2019-01-23 07:42 UTC, jaerjaerbin commented
Ok, I hit all the change suggestions commit button.

2019-01-23 22:18 UTC, isabelcosta commented
@jaerjaerbin Thank you for doing the changes! I'm a bit busy now but I will be able to help you at least until next week. Here's a tutorial I always follow for that, although it is on Slack: https://systers-opensource.slack.com/archives/CAE8QK41L/p1528726928000811 

I hope you're there, if not here's the link: http://systers.io/slack-systers-opensource/

2019-01-24 05:49 UTC, jaerjaerbin commented
@isabelcosta I was following the steps in turorial you provided me and this is what I got when trying to run this command:

`$ git branch -u upstream/develop` (develop = branch-the-PR-is-merging-to)

![image](https://user-images.githubusercontent.com/17935632/51657016-0d838780-1f71-11e9-9d0d-3defb0af053a.png)

I'll be waiting for your help next week.

2019-01-24 09:29 UTC, isabelcosta commented
@jaerjaerbin do `git fetch upstream` and then that

2019-01-25 02:58 UTC, jaerjaerbin commented
Oops! some workspace config lines in run.py I made was accidentally add. I added manually only the task dao file to commit without realize that -am would add all.

![image](https://user-images.githubusercontent.com/17935632/51722287-e71e2480-2022-11e9-8d58-8296f55206c1.png)

Now, Investigating how I can revert changes only on that file.

2019-01-27 20:42 UTC, jaerjaerbin commented
@isabelcosta check my changes please. Tell me if anything is wrong.

2019-01-28 23:39 UTC, isabelcosta requested changes
You're almost there, I just have a last change request.

Can you please (1) address my last request change please, (2) then squash commits and (3) make the commit follow our [commit style guideline](https://github.com/systers/mentorship-backend/wiki/Commit-Message-Style-Guide)

2019-01-28 23:39 UTC, isabelcosta commented on app/api/dao/task.py
> +        return {'message': 'Task was achieved successfully.'}, 200
add a blank line to the end of this file please

2019-01-29 05:53 UTC, jaerjaerbin commented
Ok @isabelcosta Sorry for all my mistakes. Thank you so much for being patient with me. I have learned a lot with making this little contribution to this project. Let me know if anything is wrong.

2019-02-01 08:49 UTC, ramitsawhney27 requested changes
Very generic return messages in the doc strings, please make it more verbose.

2019-02-02 07:17 UTC, jaerjaerbin commented
@ramitsawhney27 review it please!

2019-02-02 11:51 UTC, isabelcosta submitted a review, later dismissed
Good work @jaerjaerbin 🎉 
I'm approving this since I don't have anything else to add here.
But I'm sure @ramitsawhney27 will be able to guide you furtherer if there's something to be changed.

2019-02-04 20:12 UTC, isabelcosta submitted a review, later dismissed

2019-02-05 22:47 UTC, ramitsawhney27 requested changes

2019-02-05 22:47 UTC, ramitsawhney27 commented on app/api/dao/task.py
> +            in its value if the task creation was succesful or not as a string. The last element is a number
HTTP response code, saying a number is incorrect

2019-02-05 22:47 UTC, ramitsawhney27 commented on app/api/dao/task.py
> +            A list containing all the tasks one user has in a mentorship relation, or a two element list where the first element is
The or makes it ambiguous

2019-02-07 05:14 UTC, jaerjaerbin commented
@ramitsawhney27 changes applied. Let me know if anything is wrong.

2019-02-09 14:43 UTC, ramitsawhney27 approved these changes
Great work!

2019-02-10 11:57 UTC, isabelcosta approved these changes
It looks sooo good and descriptive 🎉 
Good work @jaerjaerbin and thank you @ramitsawhney27 for your thoughtful review!

2019-02-21 20:42 UTC, merged