test: Revoking admin status
anitab-org/mentorship-backend pull request #181
Opened 2019-01-24 16:17 UTC by sharifa2708

### Description
Added tests for revoking admin status.
Fixes #142

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
NA

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2019-01-29 01:01 UTC, isabelcosta requested changes
Thank you for sending the PR @sharifa2708 🎉 

From what I'm seeing there is some logic missing from the tests because the tests should fail when you don't send an auth header. Feel free to ask any questions regarding my change requests.

2019-01-29 01:01 UTC, isabelcosta commented on tests/admin/test_admin.py
> +    def test_revoke_admin_admin(self):
```suggestion
    def test_revoke_admin_role(self):
```

2019-01-29 01:01 UTC, isabelcosta commented on tests/admin/test_admin.py
> +        if (self.verified_user.is_admin and self.other_user.is_admin):
remove this if statement. you want to test the api, with this values regardless of their values

2019-01-29 01:01 UTC, isabelcosta commented on tests/admin/test_admin.py
> +        if(self.verified_user.is_admin and self.verified_user==self.other_user):
remove this if

2019-01-29 01:01 UTC, isabelcosta commented on tests/admin/test_admin.py
> +        if(self.verified_user.is_admin and self.other_user.is_admin == 0):
remove this if statement

2019-01-29 01:01 UTC, isabelcosta commented on tests/admin/test_admin.py
> +            actual_response = self.client.get('/admin/remove', follow_redirects=True)
to test api, you have to [create header arguments](https://github.com/systers/mentorship-backend/blob/develop/tests/users/test_api_list_users.py#L44) and then [use it on the api call](https://github.com/systers/mentorship-backend/blob/develop/tests/users/test_api_list_users.py#L46). Example: auth_header, otherwise the calls will fail, because the test user isn't authenticated. Do this for the other tests

2019-02-09 14:42 UTC, ramitsawhney27 requested changes
Also, please look into your failing build and fix it.

2019-02-09 14:42 UTC, ramitsawhney27 commented on tests/admin/test_admin.py
> +            name=user1['name'],
space between variables and operator, follow everywhere, complying to PEP8

2019-02-09 14:42 UTC, ramitsawhney27 commented on tests/admin/test_admin.py
> +    # def test_revoke_non_user(self):
No commented code in PRs please.

2019-03-05 20:53 UTC, isabelcosta commented
@sharifa2708 are you still working on this? If you're not, no problem :) We can make the issue available for other contributors.

2019-05-01 16:14 UTC, isabelcosta commented
Will close this issue and make it available again for lack of updates.
Thank you for your work here @sharifa2708 , I'm sure this will be useful for furure contributors :)

cc @ramitsawhney27

2019-05-01 16:14 UTC, closed without merging