docs: Add doc strings for MentorshipRelationDAO class and its functions
anitab-org/mentorship-backend pull request #182
Opened 2019-01-24 18:39 UTC by agarwalrounak

### Description
Added doc strings for MentorshipRelationDAO class and its functions

Fixes #159 

### Type of Change:
- Code

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

2019-01-29 01:21 UTC, isabelcosta requested changes
@agarwalrounak you're doing great!
I just left some comments for you to fix on the doc strings. Once you do that I can approve and merge this ;)

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +    """Data Access Object for mentorship relation functionalities
```suggestion
    """Data Access Object for mentorship relation functionalities.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        Args:
add line above

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        """Allows a given user to list all mentor-mentee relationships regarding them which are in the pending state.
```suggestion
        """Lists mentorship requests in pending state.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        """Allows a given user to list all mentor-mentee relationships they are currently in.
```suggestion
        """Lists current mentorship relation details.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        """Allows a given user to list all mentor-mentee relationships they have previously been into.
```suggestion
        """Lists past mentorship relations.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        """Allows a given user to delete a relationship request.
```suggestion
        """Deletes a mentorship request.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        Possible if the user created the request and it is in the pending state.
```suggestion
        Deletes a mentorship request if the current user was the one who created it and the request is in the pending state.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        """Allows a given user to reject a particular request.
```suggestion
        """Rejects a mentorship request.
```

Add a longer description 1 line below:
```
Reject mentorship request if the current user if is the receiver of the request.
```

2019-01-29 01:21 UTC, isabelcosta commented on app/api/dao/mentorship_relation.py
> +        """Allows a given user to accept a particular request.
```suggestion
        """Allows a mentorship request.
```

2019-01-29 05:30 UTC, agarwalrounak commented
Thanks for the review @isabelcosta :smiley: 
I have addressed the requested changes.

2019-01-31 19:31 UTC, agarwalrounak commented
@isabelcosta I have addressed your change requests. Please review :)

2019-01-31 21:55 UTC, isabelcosta submitted a review, later dismissed
Good work @agarwalrounak 🎉

2019-01-31 21:56 UTC, isabelcosta commented
@agarwalrounak I'll merge this in the next days. I will wait for other PRs if there's any so that I can merge more than one at a time. This is because the Database is volatile, whenever we merge something, all data will be deleted. So data related with people working on Android app, will be reset, and I'll have to create the admin user.

2019-02-01 08:48 UTC, ramitsawhney27 requested changes
The message for what each of the methods return is not descriptive enough. It's the same generic thing, it should be more verbose.

2019-02-02 07:13 UTC, agarwalrounak commented
Thanks for the review @ramitsawhney27 

I had two ideas for how the messages could be written:
1) A message corresponding to the completed action; success if mentorship relationship is established, failure if otherwise.
2) A success message if mentorship relationship is established, failure message if otherwise.

Which of the above two do you think would be more appropriate? Or any other way the message could be written?

2019-02-05 22:38 UTC, ramitsawhney27 reviewed
The first seems fine

2019-02-08 05:13 UTC, agarwalrounak commented
@ramitsawhney27 I have addressed your change requests. Please review :)

2019-02-22 04:04 UTC, agarwalrounak commented
@isabelcosta changes have been applied. Let me know if anything is wrong.

2019-02-22 06:44 UTC, ramitsawhney27 approved these changes
Great work, thanks for contributing!

2019-02-22 21:02 UTC, isabelcosta approved these changes
Good job @agarwalrounak

2019-02-22 21:03 UTC, merged