Add docstring to mentorship_relation.py
anitab-org/mentorship-backend pull request #192
Opened 2019-02-05 12:33 UTC by AyahRamahi

### Description
Added docstring to MentorRelationModel class and its functions

Fixes #168 

### Type of Change:
**Delete irrelevant options.**

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Double checked all docstrings.

### Checklist:
**Delete irrelevant options.**

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2019-02-05 22:31 UTC, ramitsawhney27 requested changes
Please investigate and fix the failing build

2019-02-05 22:31 UTC, ramitsawhney27 commented on app/database/models/mentorship_relation.py
> +        """ Returns information of mentorship as a json file. """
Json object, not file

2019-02-08 16:54 UTC, agarwalrounak requested changes

2019-02-08 16:54 UTC, agarwalrounak commented on app/database/models/mentorship_relation.py
> +    Attributes:
1 blank line before `Attributes:`

2019-02-08 16:54 UTC, agarwalrounak commented on app/database/models/mentorship_relation.py
> +            Args:
1 blank line before `Args:`

2019-02-08 16:54 UTC, agarwalrounak commented on app/database/models/mentorship_relation.py
> +    """A relatioal model the represents a mentorship.
`"""Data Model representation of a mentorship relation.` 
This should be better. Refer to: https://github.com/systers/mentorship-backend/pull/184/files/5e89077a0ed0dab3ba31bacf2b8ca3d28edc3def#r252468522

2019-02-10 10:32 UTC, AyahRamahi commented on app/database/models/mentorship_relation.py
> +    Attributes:
This blank line caused a fail in building.

2019-02-10 11:05 UTC, agarwalrounak commented on app/database/models/mentorship_relation.py
> +    Attributes:
In that case you should remove the line before `Args:` too which you just committed because that is causing the Codacity quality review to fail.

2019-02-10 11:12 UTC, agarwalrounak commented on app/database/models/mentorship_relation.py
> +    Attributes:
In that case you should remove the line before `Args:` too which you just committed because that is causing the Codacity quality review to fail.

2019-02-11 20:19 UTC, isabelcosta requested changes

2019-02-11 20:19 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +    Attributes:
add a line above

2019-02-11 20:19 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +           Args:
add a line above

2019-02-11 20:19 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +        """ Deletes the model from the database. """
```suggestion
        """ Deletes the record of mentorship relation from the database. """
```
@ramitsawhney27 ?

2019-02-11 20:19 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +        """ Saves the model to the database. """
```suggestion
        """ Saves a record of mentorship relation to the database. """
```

2019-02-12 09:50 UTC, ramitsawhney27 commented on app/database/models/mentorship_relation.py
> +        """ Deletes the model from the database. """
Yes that's much better!

2019-03-04 13:22 UTC, ramitsawhney27 approved these changes

2019-03-04 20:26 UTC, isabelcosta requested changes
You're almost done @AyahRamahi :)
Requested some style changes, just to be consistent with the rest of the docstrings.
After this, if you can squash the commits if not, I'll squash through GitHub

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +
remove this empty line

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +        """ Returns information of mentorship as a json object. """
```suggestion
        """Returns information of mentorship as a json object."""
```

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +
remove this empty line

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +
remove this empty line

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +
remove this empty line

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +        """ Saves the model to the database. """
```suggestion
        """Saves the model to the database."""
```

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +        """ Returns True if the mentorship model is empty, and False otherwise. """
```suggestion
        """Returns True if the mentorship model is empty, and False otherwise."""
```

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +
remove this empty line

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +        """ Deletes the record of mentorship relation from the database. """
```suggestion
        """Deletes the record of mentorship relation from the database."""
```

2019-03-04 20:26 UTC, isabelcosta commented on app/database/models/mentorship_relation.py
> +    """Data Model representation of a mentorship relation.
add empty line below line 9

2019-03-21 18:25 UTC, ramitsawhney27 requested changes
Please fix the Codacy PR quality complaint.

2019-03-26 00:07 UTC, isabelcosta commented
@AyahRamahi are they still working on this issue? If not we can close it and make it available for another possible contributor. If you're stuck just ask for help, so that we can see if we can help you with this.

2019-04-04 11:04 UTC, ramitsawhney27 approved these changes

2019-04-14 00:49 UTC, isabelcosta approved these changes
@AyahRamahi thank you for your contribution! 🎉

2019-04-14 00:49 UTC, merged