Added doc strings for TasksListModel class and its functions
anitab-org/mentorship-backend pull request #202
Opened 2019-02-26 15:12 UTC by sanjana11147

### Description
Created doc strings for TasksListModel class and its functions.

Fixes #167 

### Type of Change:

- Documentation

### How Has This Been Tested?
Not required.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-02-26 15:20 UTC, iulianav commented on app/database/models/tasks_list.py
> +            description: A description of the task added to the list of tasks.
Try if possible to keep the line length limit for docstrings and comments at 72 characters: https://www.python.org/dev/peps/pep-0008/#id17.

2019-02-26 15:41 UTC, agarwalrounak commented on app/database/models/tasks_list.py
> +        tasks: A lists of tasks.
```suggestion
        tasks: A list of tasks.
```

2019-02-26 15:45 UTC, agarwalrounak reviewed
Please look into your failing build and fix it.

2019-02-26 16:50 UTC, sanjana11147 commented
Please review @isabelcosta @iulianav @agarwalrounak

2019-02-27 23:03 UTC, iulianav commented
@sanjana11147 looks good to me!

2019-02-27 23:13 UTC, isabelcosta requested changes
Great job @sanjana11147  🎉 
I just requested a small change on the tasks attribute doc string.
Please squash the commits and then I can approve and merge this ;)

2019-02-27 23:13 UTC, isabelcosta commented on app/database/models/tasks_list.py
> +        tasks: A list of tasks.
```suggestion
        tasks: A list of tasks, using JSON format.
```

2019-02-27 23:13 UTC, isabelcosta commented on app/database/models/tasks_list.py
> +        tasks: A list of tasks.
I just wanted to make this clear, because of it is an important detail of tasks implementation
cc @ramitsawhney27

2019-03-17 12:34 UTC, isabelcosta commented
@sanjana11147 can you do the small change I asked and fix the Codacy warning please? They're just trailing spaces https://app.codacy.com/app/m-murad/mentorship-backend/pullRequest?prid=3174592.
After you do that I can approve and merge.

2019-03-17 14:08 UTC, sanjana11147 commented
Is it okay now? @isabelcosta

2019-03-17 14:14 UTC, isabelcosta approved these changes

2019-03-17 14:16 UTC, merged

2019-03-17 14:16 UTC, isabelcosta commented
Thank you for your contribution @sanjana11147 🎉