Fix #151 : Add tests for Assigning a new admin API
anitab-org/mentorship-backend pull request #205
Opened 2019-06-16 16:01 UTC by BadduCoder

### Description
##### Added the following tests to existing admin tests: in `tests/admin/test_dao.py`
- Assigning a user which is already an admin -> should receive a message saying that the user is already an admin
- Assigning a user as an admin, when the current user is not an admin -> should receive an error message
- Assigning a non-existent user -> should receive error message
- Revoking a user as an admin, when the current user is not an admin -> should receive an error message

#### Added error messages in `app/api/dao/admin.py`
- Added Error Message if a non admin user tries to assign someone as new admin.
- Added Error Message if a non admin user tries to revoke admin status of someone.

Fixes #151 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
`python -m unittest discover tests`

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2019-06-30 09:41 UTC, isabelcosta requested changes
@BadduCoder great work with this PR :tada: 
I requested changes for some small typos and a logic change.
After you do this, I can merge the PR.

2019-06-30 09:41 UTC, isabelcosta commented on tests/admin/test_dao.py
> +    Checks wheather a new admin can be assigned by existing admin.
```suggestion
    Checks whether a new admin can be assigned by existing admin.
```

2019-06-30 09:41 UTC, isabelcosta commented on tests/admin/test_dao.py
> +    Checks wheather a new admin can be assigned by normal user.
```suggestion
    Checks whether a new admin can be assigned by normal user.
```

2019-06-30 09:41 UTC, isabelcosta commented on tests/admin/test_dao.py
> +    Checks if a user tries to assign admin role to (him/her)self.
```suggestion
    Checks if a user tries to self-assign admin role. 
```

2019-06-30 09:41 UTC, isabelcosta commented on tests/admin/test_dao.py
> +    Checks whether a user is trying to revoke other user's admin priviledges.
```suggestion
    Checks whether a user is trying to revoke other user's admin privileges. 
```

2019-06-30 09:41 UTC, isabelcosta commented on app/api/dao/admin.py
> +                return messages.USER_ASSIGN_NOT_ADMIN, 403
```suggestion
                return messages.USER_REVOKE_NOT_ADMIN, 403
```

the message being used should be about revoking a user and not assigning

2019-06-30 09:41 UTC, isabelcosta commented on app/api/dao/admin.py
> +        #For test purposes
You can remove this comment, because this is not only for tests, but actually "production" code that was missing ;)

2019-06-30 09:41 UTC, isabelcosta commented on app/api/dao/admin.py
> +        #For test purposes
You can remove this comment, because this is not only for tests, but actually "production" code that was missing ;)

2019-06-30 09:41 UTC, isabelcosta commented on tests/admin/test_dao.py
> +        self.assertEqual((messages.USER_ASSIGN_NOT_ADMIN, 403), dao_result)
```suggestion
        self.assertEqual((messages.USER_REVOKE_NOT_ADMIN, 403), dao_result)
```
Once you fix the message being returned for revoking an admin, you'll have to fix this here

2019-06-30 09:44 UTC, isabelcosta commented
@BadduCoder  Usually we prefer that contributors fix one issue per pull request (PR). Also we prefer that you ask to work on an issue, before sending a PR, so we can better manage who works on what, and make sure "first-timers-only" are done by newcomers to the repository. As you are a newcomer its ok, that you're solving a "first-timers-only". I just wanted to let you know of this.

2019-06-30 09:50 UTC, isabelcosta commented
I will edit the description to your PR, because this actually does not fix the tests for the API, but actually fix the tests for the AdminDAO. This just means you're fixing another issue @BadduCoder

2019-07-25 15:34 UTC, BadduCoder commented
@isabelcosta Yeah sure! Thanks for the help, i will do the changes .

2019-07-30 20:22 UTC, isabelcosta submitted a review, later dismissed
Thank you for doing the changes @BadduCoder and for your contribution to our tests 🎉

2019-07-30 20:38 UTC, isabelcosta commented
@BadduCoder I will merge this PR once I review some PRs on Mentorship Android (because we still have the problem of database not being persistent, once I merge this all data used by android contributors is gone)

2019-08-01 16:10 UTC, BadduCoder commented
@isabelcosta Sure! Would love to contribute more :grinning:

2019-08-21 22:50 UTC, isabelcosta commented
@BadduCoder you should commit the last commit from the new issue you're working on, on a separate branch and pull request, to separate the scope of code review of both issues. Can you please remove this commit from this PR? This made my previous review obsolete :/

2019-08-21 23:44 UTC, BadduCoder commented
Yes @isabelcosta, I have reverted back the commit. Next time i will take care about this for sure. Thanks for helping out!

2019-08-21 23:46 UTC, isabelcosta approved these changes

2019-09-18 22:26 UTC, merged