Fix for #154, added documentation
anitab-org/mentorship-backend pull request #208
Opened 2019-07-31 15:57 UTC by amnoweb

### Description
Added doc strings to the code explaining the UserDAO class and its functions, following python doc string conventions.

Fixes #154 

### Type of Change:
- Documentation

### How Has This Been Tested?
Did not require tests, as it was not a change to the functioning code but simply documentation.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand 
- [x] I have made corresponding changes to the documentation

2019-08-19 20:52 UTC, isabelcosta requested changes
@amnoweb thank you for this contribution!
I left two change suggestions. Let me know when you change it and feel free to discuss if you have any better suggestion.

2019-08-19 20:52 UTC, isabelcosta commented on app/api/dao/user.py
> +            A list with two elements. The first element is a dictionary containing a key 'message' containing a string which indicates whether or not the user was created successfully. The second is
```suggestion
            A tuple with two elements. The first element is a dictionary containing a key 'message' containing a string which indicates whether or not the user was created successfully. The second is the HTTP response code.
```

What is returned is a tuple and not a list.

2019-08-19 20:52 UTC, isabelcosta commented on app/api/dao/user.py
> +            A list with two elements. The first element is a dictionary containing a key 'message' containing a string which indicates whether or not the user was created successfully. The second is
```suggestion
            A tuple with two elements. The first element is a dictionary containing a key 'message' containing a string which indicates whether or not the user was created successfully. The second is the HTTP response code.
```

What is returned is a tuple and not a list.

2019-08-20 18:04 UTC, amnoweb commented
@isabelcosta, your changes looked good so I just committed them, hopefully that works!

2019-08-20 20:21 UTC, isabelcosta approved these changes
Thank you @amnoweb for doing these changes 🎉

2019-09-18 22:35 UTC, merged