Added docstrings to user class.
anitab-org/mentorship-backend pull request #214
Opened 2019-10-03 18:38 UTC by Samiratu

### Description
We need to have doc strings for UserModel class, attributes and functions. You can find this file app/database/models/user.py.
Fixes # [ISSUE]
 Added doc strings for UserModel class, attributes and its functions (file: app/database/models/user.py).
### Type of Change:
- Documentation
### How Has This Been Tested?
followed the style guide for doc strings in python by Google.
### Checklist:
**Delete irrelevant options.**
[ ] My PR follows the style guidelines of this project.
**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

2019-10-03 18:41 UTC, prachi1210 requested changes

2019-10-03 18:41 UTC, prachi1210 commented on app/database/models/user.py
> +        """"Inits userModel class with name, username, password, email, and terms_and_conditions_checked. """
Can you change 'init's to 'initialises'

2019-10-03 18:43 UTC, isabelcosta commented on app/database/models/user.py
> +        """"Inits userModel class with name, username, password, email, and terms_and_conditions_checked. """
Also there's an extra `"`

2019-10-03 18:46 UTC, prachi1210 approved these changes

2019-10-03 18:46 UTC, merged

2019-10-04 18:41 UTC, isabelcosta commented
Closes #169