created early CLI prototype
anitab-org/mentorship-backend pull request #283
Opened 2019-12-16 00:28 UTC by bartekpacia

### Description
In my opinion, working with the backend using Postman isn't really a great experience. `POST` Register user with a real email, open mailbox and confirm, then `POST` login. And if you want to use many other endpoints, you also need JWT for a user. And that user sometimes needs to be an admin (when u perform admin-like things). Huh, lots of work.

I've seen issue #275, then #78, and thought...let's do it!
I decided to go with [Click](https://click.palletsprojects.com/en/7.x/), as it's already by Flask out-of-the-box (Flask uses it internally for its own stuff, too).
From an "architectural side" I use [Blueprints](https://flask.palletsprojects.com/en/1.0.x/blueprints/). They fit this use case quite well and are fairly simple.

And here it is, an early CLI prototype.

Features:
- dropping and creating database
- populating database with initial data
- pleasant and easy creation of new users
- easy listing of all users and specific user (by id, username and email)
- listing, assigning and revoking admins

Fixes #275, #78

### Type of Change:
- Code
- Quality Assurance
- User Interface [I'm not sure here...CLI is kinda like UI for a developer)
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?
Tested manually, but as said above, this is an early prototype. Unit tests are missing, functionality isn't guarranteed to work. Use at you own risk (in the worst case you'll nuke your local database).

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [x] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

PS Any feedback would be greatly appreciated. I'm coming from NodeJS-land and still feel quite new and uncertain in this astonishing Python-Flasky world.

2019-12-16 00:39 UTC, bartekpacia commented
@isabelcosta I think it may interest you

2019-12-16 19:20 UTC, isabelcosta reviewed
Thank you for tackling this problem @bartekpacia !This is not  code review, per say, but a general comment for now. As the issue here is not part of GCI task, then this PR should be targeting `develop` branch.

2019-12-16 20:27 UTC, bartekpacia commented
Sure, changed :)

2019-12-21 00:12 UTC, bartekpacia commented
I've recorded [video demonstration](https://youtu.be/m4yioyeEOyM).

2019-12-27 10:26 UTC, bartekpacia commented
@isabelcosta @BadduCoder I'd love to hear your opinion and suggestions 😄 (if you have time of course)

2020-03-23 20:34 UTC, isabelcosta commented
@bartekpacia This is my first time looking and actually thinking about this, so I just watched your video and this is pretty amazing :) And I just love that this helps to create a set of users just from a JSON file.
I feel that this will require some changes, I will review soon. Do you wish to continue with this issue, if I end up proposing changes?

I already learned new things from this PR.

2020-03-23 20:37 UTC, bartekpacia commented
@isabelcosta Oh, this PR. I remember how much work I put into this:) happy to hear you like it. I'd love this to be developed further because it has the potential of saving many hours of rather tedious work (I remember I was using this very often during GCI for my private testing purposes).

I'll wait for your opinions and will try to find some time to polish this. Hopefully it'll make its way into master.

2020-03-23 20:37 UTC, bartekpacia commented
*i accidentaly closed*👀

2020-03-23 21:22 UTC, isabelcosta commented
I accidentally opened 👀

2020-05-20 10:05 UTC, Hyper-Matrix submitted a review, later dismissed

2020-05-20 10:07 UTC, robotjellyzone commented
hi @bartekpacia could you mind to resolve the conflicts in this PR so, that it can be ready to merge :)

2020-05-23 17:46 UTC, bartekpacia commented
@robotjellyzone Sure, resolving now.

2020-05-23 18:49 UTC, bartekpacia commented
I've spent 1 hour trying to setup dev env for this project, but some extremely strange bugs appear.
Finally, I resolved it using GitHub's website editor, so I couldn't test it :/

2020-05-23 18:57 UTC, bartekpacia commented
at least checks are passing🙏

2020-07-16 17:09 UTC, bartekpacia commented
@isabelcosta any response on this? I'd really love to see this get merged.
(It might need some testing & updates, but I'm willing to provide necessary help)

2020-08-04 18:20 UTC, bartekpacia commented
just a ping @isabelcosta :)

2020-08-04 18:43 UTC, isabelcosta requested changes
Ok after a quick look at this, here's what I would suggest for this PR to be better:
- Add instructions on how to work with this tool (commands, and one example per command)on a markdown file under `docs` folder. In the end link it in the README somehow.
- solve merge conflicts (e.g.: we are now using flask-restx instead of flask-restplus)
- if possible, add unit tests for the cli options you created
- (nice to have) add typehints :)

@bartekpacia thank you for chasing me to review this 🙈 , this seems great work and to ease developer's work, without affecting functionalities of the project.

2020-08-04 18:43 UTC, isabelcosta commented on run.py
> +
can you add a comment here, to explain you are adding cli options or something, also should this be inside or outside the create_app()?

2020-08-04 18:43 UTC, isabelcosta commented on run.py
> +load_dotenv(verbose=True)
is this really needed?

2021-02-20 18:47 UTC, vj-codes commented
Closing this due to inacativity also author is not assigned to the issue .

2021-02-20 19:45 UTC, bartekpacia commented
@vj-codes , I'd really like to finish this feature:) Please consider reopening and assign me – I will try to work on it when I have time. 
Are there any hard limits on the duration of how long can a PR be worked on by an author?

2021-02-20 19:53 UTC, vj-codes commented
@bartekpacia suree I'll assign it to you!
No limits on duration but you should update the progress or approx time required so the PR is not inactive otherwise it could be closed by someone again 👀

2021-02-20 19:53 UTC, vj-codes commented
@bartekpacia also there are some merge conflicts do solve them when you have time, thanks!

2021-02-20 19:54 UTC, bartekpacia commented
That's great, thank you:)

2023-12-01 23:20 UTC, bartekpacia commented
I'm looking at the list of all my PRs and this is one of the oldest ones. Unfortunately I don't see a chance on getting this merged, last change (d878a013060785a0a077ea16342707b501880827) was made more than a year ago, so I'm going to reluctantly close this PR. Maybe, hopefully, in the future someone will be willing to pick this up.

Good old Google Code-in times. Thanks to everyone involved!

2023-12-01 23:20 UTC, closed without merging