feat: mentorship accept -> send mail
anitab-org/mentorship-backend pull request #302
Opened 2019-12-21 14:07 UTC by pascaaaal

### Description
I added a functionality, that sends a mail to the user when the mentorship relation is accepted.

Fixes # [ISSUE]

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I just ran the official test <code>python -m unittest discover tests</code> and it worked.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2019-12-25 04:57 UTC, xprilion requested changes
Hi, kindly go through my comments on the code :) 

I believe this is near completion but you need to use the provided methods in the existing code for best modularity.

2019-12-25 04:57 UTC, xprilion commented on app/api/dao/mentorship_relation.py
> +        mail.send(msg)
Hi, can you please use the suitable replacement for this from the `email_utils.py` ?

2019-12-25 04:57 UTC, xprilion commented on templates/email_mentorship_accepted.html
> +<p>Congratulations, your Mentorship Relation has been accepted!</p>
Can you please add who accepted the mentorship relationship? Also, having a link to the profile of the mentor would be good for quick actions!

2020-02-12 14:02 UTC, BadduCoder commented
Close due to #327 merge.
Thank you for your contribution!

2020-02-12 14:02 UTC, closed without merging