test: added tests mentioned in issue #305
anitab-org/mentorship-backend pull request #321
Opened 2019-12-25 11:14 UTC by Goutam192002

### Description
Added tests mentioned in issue #305 

Fixes #305 

### Type of Change:

- Code
- Quality Assurance

### How Has This Been Tested?
To check if the user is trying to create a task on a unaccepted state relation. I choose a task which is in unaccepted state and try to create a task. It returns a 400.
To check if the user is trying to create a task with empty description. I try to create a task with no description which again returns a 400.
To check if the user is trying to create a task with an expired auth token. I create a auth header in which the token has already expired. In this case the api returns a 401.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

2019-12-25 18:45 UTC, Tlazypanda requested changes
@Goutam192002 Some changes required on the pr :)

2019-12-25 18:45 UTC, Tlazypanda commented on tests/tasks/tasks_base_setup.py
> +        self.third_user = UserModel(
Changes are not required in this file.

2019-12-25 18:45 UTC, Tlazypanda commented on tests/tasks/test_api_create_task.py
> +        expected_response = messages.UNACCEPTED_STATE_RELATION
message returned should be `MENTORSHIP_RELATION_DOES_NOT_EXIST`

2019-12-25 18:45 UTC, Tlazypanda commented on tests/tasks/test_api_create_task.py
> +    def test_user_involved_in_mentorship_relation_creates_task(self):
rename method to `test_user_not_involved_in_mentorship_relation_creates_task`

2019-12-25 18:45 UTC, Tlazypanda commented on tests/tasks/test_api_create_task.py
> +        self.assertEqual(400, actual_response.status_code)
Status code returned should be 404

2019-12-25 18:45 UTC, Tlazypanda commented on tests/test_data.py
> +user3 = {
Changes not required here

2019-12-26 00:39 UTC, Goutam192002 commented
Done 👍

2019-12-26 12:00 UTC, Tlazypanda approved these changes
Approved :)

2020-02-06 19:57 UTC, isabelcosta commented
Thank you so much for your contribution @Goutam192002  🎉 
I'm closing this PR because we decided to merge #310

2020-02-06 19:57 UTC, closed without merging