test: Cancel Mentorship Relation
anitab-org/mentorship-backend pull request #323
Opened 2019-12-25 22:06 UTC by mini-mini-milo

Tested valid user cancelling valid task with missing authentication token
Tested valid user cancelling valid task with expired authentication token

### Description
Added tests for cancelling mentorship relations:
1. valid user cancelling valid task with missing authentication token (fail)
2. valid user cancelling valid task with expired authentication token (fail)
Fixes # [307]

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran locally using "python -m unittest discover tests"

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2019-12-26 11:49 UTC, Tlazypanda requested changes
Tests missing from this [table](https://github.com/systers/mentorship-backend/wiki/Quality-Assurance#cancel-relation).Can you add those tests?

2019-12-26 14:43 UTC, isabelcosta requested changes
Hey @mini-mini-milo if this PR is part of the GCI competition, I believe one of the steps is that this PR should be targeting the `gci-dev` branch. You can change this by clicking the edit button next to the pull request title, and change base branch from `develop` to `gci-dev`.

2019-12-26 22:39 UTC, isabelcosta requested changes
Hey @mini-mini-milo I left some request changes. Its small things, you are almost done!
Thank you for your contribution 🙌

2019-12-26 22:39 UTC, isabelcosta commented on tests/mentorship_relation/test_api_cancel_relation.py
> +    def test__mentee_cancel_token_missing(self):
This test and the test above are exactly equal, so this one can be deleted.
Can you please delete this?

2019-12-26 22:39 UTC, isabelcosta commented on tests/mentorship_relation/test_api_cancel_relation.py
> +    def test__mentor_cancel_token_missing(self):
```suggestion
    def test_mentor_cancel_token_missing(self):
```

2019-12-26 22:39 UTC, isabelcosta commented on tests/mentorship_relation/test_api_cancel_relation.py
> +    def test__mentor_cancel_token_expired(self):
```suggestion
    def test_mentor_cancel_token_expired(self):
```

2019-12-26 22:39 UTC, isabelcosta commented on tests/mentorship_relation/test_api_cancel_relation.py
> +    def test__mentee_cancel_token_expired(self):
```suggestion
    def test_mentee_cancel_token_expired(self):
```

2019-12-26 22:39 UTC, isabelcosta commented on tests/test_data.py
> +}
Please add a blank line here in the end of the file

2019-12-26 22:39 UTC, isabelcosta commented on tests/mentorship_relation/test_api_cancel_relation.py
> +    def test__user_not_in_mentorship(self):
```suggestion
    def test_user_not_involved_tries_to_cancel_relation(self):
```

2019-12-26 22:40 UTC, isabelcosta commented on tests/mentorship_relation/test_api_cancel_relation.py
> +    def test__mentor_cancel_token_missing(self):
I know there are other tests in this file with double `_`, it must have been a typo that stayed. we can fix it later.

2019-12-26 23:05 UTC, isabelcosta requested changes
You deleted one test that was ok, I just asked you to remove one of the tests which was `test__mentor_cancel_token_missing`.
You also removed `test__mentee_cancel_token_expired` test, that was needed. Can you please put that test again?

2019-12-27 11:22 UTC, Tlazypanda approved these changes
Approved :)

2020-01-30 23:25 UTC, isabelcosta commented
Thank you for your contribution here @mini-mini-milo  🎉 
I'm going to close this PR, since we decided to merge another one.

2020-01-30 23:25 UTC, closed without merging