Increase JWT token expiration delta
anitab-org/mentorship-backend pull request #35
Opened 2018-06-05 00:16 UTC by isabelcosta

### Description

Increased JWT access token expiration delta to 1 week.

Fixes #30 

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

I logged a user, with a value for the expiration delta of 10 seconds, to make sure if I was changing the right value.
Then I changed the value to 1 week and validated the value had changed.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2018-06-06 06:37 UTC, m-murad requested changes

2018-06-06 06:37 UTC, m-murad commented on app/api/resources/user.py
> +        The user can login with username + password.
(username or email) + password

2018-06-06 12:50 UTC, m-murad approved these changes

2018-06-07 07:46 UTC, Dilu9218 approved these changes

2018-06-07 09:35 UTC, m-murad commented
@isabelcosta
 Please resolve conflict

2018-06-07 23:01 UTC, isabelcosta commented
@m-murad will solve these now.

2018-06-07 23:56 UTC, isabelcosta commented
@m-murad @Dilu9218 Just fixed the merge conflicts and added a mini test condition, to test the expiration delta configuration for every env (Dev, Test and Prod)

2018-06-08 06:29 UTC, m-murad commented
@isabelcosta 
Can we send the expiry date of the token along with the response?

2018-06-08 06:31 UTC, merged

2018-06-08 09:49 UTC, isabelcosta commented
@m-murad sure I can create the issue.