feat: Improve Change Password Functionality
anitab-org/mentorship-backend pull request #353
Opened 2019-12-29 15:32 UTC by mini-mini-milo

adds new error message
Changes password only when the new password does not match the current one

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [319]

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran PUT/user/change_password on a local server 

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**

2019-12-29 16:09 UTC, sara-02 requested changes
Please update the spaces in the string and redo the screenshot for password matching case.

2019-12-29 16:09 UTC, sara-02 commented on app/messages.py
> +                                         "password as current one."}
Please a space at the beginning of lines 127 and 128 and not the end of the lines 126/127 respectively inside the string.

2019-12-29 16:29 UTC, sara-02 approved these changes

2020-02-15 18:02 UTC, isabelcosta commented
I'm closing this because of #316 merge.
Thank you for your contribution!

2020-02-15 18:02 UTC, closed without merging