[Program: GCI] (Comment task - Part 1/2) prepare comment task database table. [Mentorship - Backend]
anitab-org/mentorship-backend pull request #368
Opened 2019-12-31 13:01 UTC by asawesome07

### Description
Added task comment model and DAO. This is part 1 of 2 of complete integration of task comment table.

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I tested this using `python -m unittest discover tests`

Here's a screenshot
![Capture](https://user-images.githubusercontent.com/29257061/71584311-1218ce80-2b38-11ea-9c45-17e5d3317d98.PNG)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] Update Postman API at /docs folder
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2019-12-31 13:22 UTC, annabauza approved these changes

2020-02-09 18:45 UTC, annabauza commented
Can you also please resolve conflicts here? I'm happy to help if you are not sure.

2020-02-09 18:49 UTC, asawesome07 commented
> Can you also please resolve conflicts here? I'm happy to help if you are not sure.

yeah, could you help?

2020-02-09 18:53 UTC, asawesome07 commented
> > Can you also please resolve conflicts here? I'm happy to help if you are not sure.
> 
> yeah, could you help?

nevermind, made the changes, no conflicts now.

2020-02-09 18:54 UTC, annabauza commented
Thanks, if you could please to check why test fails I would be grateful

2020-02-09 18:54 UTC, annabauza commented
Thanks, if you could please to check why test fails I would be grateful

2020-02-09 18:57 UTC, asawesome07 commented
> Thanks, if you could please to check why test fails I would be grateful

it looks like, I merged the user_dashboard_details as well, which I guess doesn't exist and causes the error. I would be grateful if you could help out, I am studying for a test that this tomorrow

2020-02-09 19:26 UTC, annabauza commented
sure thing you mind to give me write permission to your repo?

2020-02-09 19:29 UTC, asawesome07 commented
> sure thing you mind to give me write permission to your repo?

I have sent you an invite

2020-02-09 19:33 UTC, annabauza requested changes
I have found the issue.

2020-02-09 19:33 UTC, annabauza commented on app/api/models/mentorship_relation.py
> +    'comment': fields.String(required=True, description='Comment value for task comment')
missing brackets here

2020-02-09 21:54 UTC, annabauza approved these changes

2020-02-11 22:55 UTC, annabauza commented
closing due to #356 merge

2020-02-11 22:55 UTC, closed without merging