[Program: GCI] Create doc strings for each API
anitab-org/mentorship-backend pull request #406
Opened 2020-01-19 20:22 UTC by IlyaMaier

### Description
- Added doc strings for each API in order to improve Swagger documentation

I provided screenshots for some APIs as it would be too long for including every single API. 

Fixes #404 

### Type of Change:
- Code
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
The changes were tested using Swagger UI.

### Screenshots:
![Screenshot (112)](https://user-images.githubusercontent.com/34242059/72687760-6b559b80-3b01-11ea-8537-c2b71d3973a2.png)
![Screenshot (113)](https://user-images.githubusercontent.com/34242059/72687761-6bee3200-3b01-11ea-9fb8-024e60771e42.png)
![Screenshot (114)](https://user-images.githubusercontent.com/34242059/72687763-6c86c880-3b01-11ea-8d5b-b15c62f75ece.png)
![Screenshot (115)](https://user-images.githubusercontent.com/34242059/72687764-6d1f5f00-3b01-11ea-8c67-98ae415c4fb7.png)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2020-01-19 20:45 UTC, isabelcosta requested changes
Hey @IlyaMaier can you please remove the changes in the admin and user API files, since the issue and GCI task you are solving is only referring to the mentorship relation API. We tend to keep PRs changes in the scope of the issue they are solving.

2020-01-19 20:45 UTC, isabelcosta commented on app/api/resources/admin.py
> +        must exist and do not be an admin.
```suggestion
        must exist and not be an admin.
```

2020-01-19 21:05 UTC, IlyaMaier commented
> Hey @IlyaMaier can you please remove the changes in the admin and user API files, since the issue and GCI task you are solving is only referring to the mentorship relation API. We tend to keep PRs changes in the scope of the issue they are solving.

@isabelcosta I've done the required changes :)

2020-01-19 21:11 UTC, sara-02 requested changes
Missed a typo

2020-01-19 21:11 UTC, sara-02 commented on app/api/resources/mentorship_relation.py
> +        Both users must be available and the duration of th relationship must
`the`

2020-01-19 21:13 UTC, IlyaMaier commented on app/api/resources/mentorship_relation.py
> +        Both users must be available and the duration of th relationship must
oh yes! Thank you! Will change it rn. 😅

2020-01-19 21:13 UTC, sara-02 commented
Also, what about the inconsistency of the periods? Any thoughts there?

2020-01-19 21:15 UTC, IlyaMaier commented
> Also, what about the inconsistency of the periods? Any thoughts there?

@sara-02 What exactly do you mean? The periods are always at the end of each sentence in the actual description. They are not displayed in the title, therefore are redundant

2020-01-19 21:18 UTC, IlyaMaier commented on app/api/resources/mentorship_relation.py
> +        Both users must be available and the duration of th relationship must
have fixed that :)

2020-01-19 21:22 UTC, IlyaMaier commented
@sara-02 I thought about it one more time. You are right. I mean if the periods don't change anything, why not to add them to have a clear structure of all sentences. So I added them :)

2020-01-19 21:30 UTC, sara-02 approved these changes

2020-01-19 21:31 UTC, sara-02 commented
I will wait for @isabelcosta to add her final comments and approve the PR and task.

2020-01-19 22:58 UTC, isabelcosta approved these changes
Great work @IlyaMaier ! thank you for your contribution :)

2020-01-20 02:32 UTC, Anjali05 commented
I think I am tagged in this by mistake?

2020-01-20 03:06 UTC, IlyaMaier commented
> I think I am tagged in this by mistake?

Oh yes! Sorry!

2020-02-04 19:03 UTC, isabelcosta commented
Thank you so much for your contribution @IlyaMaier during the GCI contest 🙌 
I'm closing this PR, since we decided to merge PR #405

2020-02-04 19:03 UTC, closed without merging