changed status code of create task  ,comment task created to 201 ,
anitab-org/mentorship-backend pull request #462
Opened 2020-02-28 01:03 UTC by srivastava9

### Description
changed docs to reflect the same and test case to assert for this.

Fixes #448

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Ran the test on the code and also checked it creating comment task and creating task

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2020-02-28 01:04 UTC, srivastava9 commented
@isabelcosta  @BadduCoder  Could you please review this pr. :)

2020-02-28 18:27 UTC, sumit-badsara reviewed
This only changes the response, you also need to update the documentation.
And verify the changes by checking Swagger UI while running on local.
If you have any issues, you can ask on zulip, or comment down here. :smile: 

Also, I observed a strange error, I might raise an issue regarding that, this issue may effect you too.
So, I guess that need to be solved before this issue. I will put a reference here, once I create it.

2020-02-28 20:19 UTC, srivastava9 commented
@BadduCoder I have already updated the swagger docs and test cases and i have also checked it by running on local machine as well as creating a task.
I would love to work on that error. :)

2020-03-04 19:15 UTC, isabelcosta requested changes
@srivastava9 thank you for your contribution 🎉 
Could you please keep this commit to the change requested by the issue? You have some formatting code in this PR. this should come from other PRs dedicated to styling.

2020-03-10 12:43 UTC, sumit-badsara commented on docs/swagger.json
> +                    "201": {
@srivastava9 This shouldn't be done manually in `swagger.json`

2020-03-15 14:34 UTC, isabelcosta commented on docs/swagger.json
> +                    "201": {
Could you undo this change please? @srivastava9

2020-03-15 15:13 UTC, srivastava9 commented on docs/swagger.json
> +                    "201": {
Sure I can look into this and change accordingly. :)

2020-03-15 16:00 UTC, srivastava9 commented
I have updated my pr accordingly .
@isabelcosta @BadduCoder  Do have a look :)

2020-03-15 16:07 UTC, isabelcosta approved these changes
Great work @srivastava9 🎉 
Thank you for your contribution!

2020-03-16 12:44 UTC, sumit-badsara approved these changes

2020-03-16 18:18 UTC, merged