added-create-task-table
anitab-org/mentorship-backend pull request #499
Opened 2020-03-15 18:38 UTC by AjayThakur12

### Description
Create d Quality Assurance table for Create Task API in docs/quality-assurance-test-cases.md

Fixes #472 

### Type of Change:
- Documentation

### How Has This Been Tested?
I checked both android - mentorship code services code and backend API code

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation
- [ ] Update Postman API at /docs folder

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-03-16 20:57 UTC, ramitsawhney27 submitted a review, later dismissed
Can we keep consistent spacing?

2020-03-17 06:27 UTC, AjayThakur12 commented
@ramitsawhney27  this is how it look after adding not able to understand your point
<img width="662" alt="yui" src="https://user-images.githubusercontent.com/29337604/76828155-5027b380-6846-11ea-9963-c391eab638de.png">

2020-03-17 21:23 UTC, ramitsawhney27 commented on docs/quality-assurance-test-cases.md
> +|Create a task if there is a valid relation exist between user and mentor and relation state is accepted | Success |
I meant from a source markdown perspective as well. Look at this line

2020-03-17 23:15 UTC, isabelcosta requested changes
Thank you for contributing to our documentation @AjayThakur12 🎉 
I left some notes to make the text a little more clear.
Here is one more case for you to add:
- creating a task without a description (either empty or not in the request body at all)

2020-03-17 23:15 UTC, isabelcosta commented on docs/quality-assurance-test-cases.md
> +| Create a task if there is no relation between user and mentor | Fail |
I am not sure if anyone could even test this, can you be more specific? I think what you want to say here is something like:
create a task when logged user is not involved in the relation

2020-03-17 23:15 UTC, isabelcosta commented on docs/quality-assurance-test-cases.md
> +| Create a task if relation state is not accepted | Fail |
```suggestion
| Create a task if relation state is different than accepted | Fail |
```
its more clear like this, I think

2020-03-17 23:15 UTC, isabelcosta commented on docs/quality-assurance-test-cases.md
> +|Create a task if there is a valid relation exist between user and mentor and relation state is accepted | Success |
```suggestion
| Create a task for a relation, in the accepted state, between logged user and another user | Success |
```

2020-03-17 23:35 UTC, isabelcosta commented
Because of this PR I detected a bug on the backend :D I am happy, because it means this is useful!
https://github.com/anitab-org/mentorship-backend/issues/507

2020-03-18 09:50 UTC, AjayThakur12 commented
@isabelcosta  thank you for your review I will make required changes

2020-03-23 20:01 UTC, isabelcosta commented
@AjayThakur12 you also have to fix merge conflicts. Do you need any help with this PR? Asking as there are no updates

2020-03-24 05:57 UTC, AjayThakur12 commented
@isabelcosta  sorry for the delay, I  will complete  task by today.

2020-04-07 19:54 UTC, developer22-university commented
@isabelcosta  is this resolved? i can help if required

2020-04-12 15:36 UTC, isabelcosta approved these changes
Looks good @AjayThakur12 :) thank you for your contribution 🎉

2020-04-12 15:39 UTC, merged

2020-04-12 15:40 UTC, isabelcosta commented
@AjayThakur12 great work 👏 your PR was merged!