Updated rREADME.md
anitab-org/mentorship-backend pull request #502
Opened 2020-03-17 05:28 UTC by Adarsh-NP

Changed the link assosciated with environment variables from wiki to the repo link as mentioned in the issue.

### Description
Earlier the link explaining the exporting of environment variables was to a wiki page which asked to refer to mentorship-backend/docs/environment-variables.md. I simply connected the link directly to the file thus skipping the wiki link.

Fixes #494 

### Type of Change:
- Documentation

### How Has This Been Tested?
The new link takes to the appropriate directory.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

2020-03-17 21:44 UTC, isabelcosta requested changes
Thank you for your contribution @Adarsh-NP !
Could you use relative paths? This is so if you are on your fork or we use another branch in the future then this is not tightly coupled to `develop` branch. Makes sense?
Also could you please follow our [Commit Message Style Guide](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide) as this is part of our project guidelines.

2020-03-17 21:44 UTC, isabelcosta commented on README.md
> + - [Export Environment Variables](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md)
```suggestion
 - [Export Environment Variables](docs/environment-variables.md)
```
what about using relative path? I think this could work :)

2020-03-17 21:44 UTC, isabelcosta commented on README.md
> +make sure you exported the following [environment variables](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md):
```suggestion
make sure you exported the following [environment variables](docs/environment-variables.md):
```
relative path

2020-03-17 21:44 UTC, isabelcosta commented on README.md
> +1. Make sure you exported the following [environment variables](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md) to '.env' file
```suggestion
1. Make sure you exported the following [environment variables](docs/environment-variables.md) to '.env' file
```

2020-03-22 13:42 UTC, isabelcosta commented
@Adarsh-NP why did you close this issue? Do you wish to stop working on this issue?

2020-03-22 13:44 UTC, isabelcosta approved these changes
@Adarsh-NP this is great, but can you squash your commits and follow our commit style guideline?
Let me know if you need any help with this

2020-03-22 18:58 UTC, Adarsh-NP commented
@isabelcosta yeah ma'am, regarding commit message guidelines what else do I need to change, I don't seem to understand it.

2020-03-23 18:01 UTC, isabelcosta commented
@Adarsh-NP your main git commit message is `Updated Readme.md`, when following our Commit Message Style Guideline, that you can find on our Wiki and the CONTRIBUTING.md, your message should be something like: `docs: update env variables link on readme`.

Are you able to squash and amend the commit message?

2020-04-12 12:47 UTC, merged

2020-04-12 12:47 UTC, isabelcosta commented
@Adarsh-NP your pull request was merged 🎉 thank you for your contribution 👏