Refactor: Improve Swagger Docs description
anitab-org/mentorship-backend pull request #516
Opened 2020-03-28 15:27 UTC by EfthymiaKostaki

### Description
Updated Swagger Docs description for including more information about the project.
Fixes # [#482 ]

### Type of Change:
- User Interface

### How Has This Been Tested?
When the server is running the updates are immediately visible.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

2020-03-28 17:40 UTC, isabelcosta commented
@EfthymiaKostaki happy to see you figured out how to solve this issue :) Can you please include a screenshot of how the Swagger UI description looks like now? As per our contribution guidelines, when you do a change that involves UI change, its required that you include an image on the PR description. Can you please do that?

2020-03-28 19:16 UTC, EfthymiaKostaki commented
@isabelcosta  Thank you for your comment. I edited my pull request and added a screenshot of the updated description. Is there anything I could improve?

2020-03-30 19:37 UTC, isabelcosta commented
I will wait until you do the removal of the Default namespace, and then I can properly review @EfthymiaKostaki

2020-03-31 10:44 UTC, EfthymiaKostaki commented
@isabelcosta  Hello, I have updated this pull request with the commit for the default namespace issue.

2020-04-01 19:50 UTC, naveennvrgup submitted a review, later dismissed
Checked the PR locally. Fixes the issue as descripted.

2020-04-01 20:50 UTC, isabelcosta requested changes
@EfthymiaKostaki this is great, I just suggest adding the little description for the app there for a little more context :)

2020-04-01 20:50 UTC, isabelcosta commented on app/api/api_extension.py
> +    + "The main repository of the Backend System can be found here: https://github.com/anitab-org/mentorship-backend \n \n"
Could you add before this line the description of the app?

**Here it is:** Mentorship System is an application that matches women in tech to mentor each other, on career development, through 1:1 relations during a certain period of time.

2020-04-01 20:51 UTC, isabelcosta commented
@naveennvrgup thank you a lot for reviewing and testing this! I would love to see more of this from contributors :) I really appreciate your testing here. I think I will start adding a label to issues that need testing to guide you all.

2020-04-02 09:56 UTC, EfthymiaKostaki commented
@naveennvrgup Thank you for your review! I don't know why GitHub shows message I dismissed your technical review, maybe it's because I added a new commit message.

@isabelcosta I have added the description of the app.

2020-04-05 18:51 UTC, isabelcosta commented
> @naveennvrgup Thank you for your review! I don't know why GitHub shows message I dismissed your technical review, maybe it's because I added a new commit message.

It is because of the new commit, so that is ok ;)

> @isabelcosta I have added the description of the app.

Thank you so much 👏

2020-04-05 18:53 UTC, isabelcosta approved these changes
Great work @EfthymiaKostaki 👏 
Thank you for your contribution!

2020-04-07 20:13 UTC, rpattath commented
Tested the changes and seeing the updated documentation.

![Screenshot from 2020-04-07 16-10-41](https://user-images.githubusercontent.com/26095715/78714894-970b4500-78ea-11ea-9069-4835e00685bf.png)

2020-04-07 20:29 UTC, isabelcosta commented
If you wish @rpattath you can leave a review like a comment, without approval. I know that GitHub counts that as a contribution, whereas comments do not count. I would love to these contributions of yours recorded as such.

![image](https://user-images.githubusercontent.com/11148726/78716431-c9cb3280-7916-11ea-9723-6cfbdac97af3.png)

2020-04-07 20:29 UTC, isabelcosta commented
Very very good @rpattath thank you so much for your testing :D

2020-04-07 20:30 UTC, isabelcosta commented
@foongminwong could you please review this and if you do merge, can you make sure the commit follows the guideline and includes the id of the PR?

2020-04-07 20:37 UTC, rpattath commented
> If you wish @rpattath you can leave a review like a comment, without approval. I know that GitHub counts that as a contribution, whereas comments do not count. I would love to these contributions of yours recorded as such.
> 
> ![image](https://user-images.githubusercontent.com/11148726/78716431-c9cb3280-7916-11ea-9723-6cfbdac97af3.png)

I did not know that, thank you for the tip !

2020-04-07 20:46 UTC, isabelcosta commented
feel free to try that out here if you want and then check on your GitHub profile if you have an activity item listed saying you "Reviewed a pull request"

2020-04-12 12:44 UTC, merged

2020-04-12 12:45 UTC, isabelcosta commented
@EfthymiaKostaki PR was merged 👏 thank you for your contribution here 🎉