issue 507 user not involved in relationship check added along with unit tests
anitab-org/mentorship-backend pull request #520
Opened 2020-03-31 15:33 UTC by Ashokrayal

### Description
A Check is implemented which validates if the user is either mentee or mentor for the relationship. Unit test case is also added

Fixes # #507 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Reproduced the bug with given steps. The bug was reproducible. After the fix, it was working as expected.

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have made corresponding changes to the documentation
- [X] Update Swagger documentation

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2020-03-31 15:47 UTC, Ashokrayal commented
Hi @isabelcosta, @sara-02, @ramitsawhney27 

Please review and merge.  I was working on this issue. I had code ready form 6 days back but I waiting for my PR #513 to be merged. I also mentioned the same in that PR.

Also, my implementation is slightly better and passed all checks.

I am interested in contributing but to get a PR reviewed and merged has become hard. I don't know but maybe It is because of coronavirus at this time. 

Thanks

2020-03-31 23:02 UTC, isabelcosta requested changes
@Ashokrayal thank you so much for your contribution here :)
I left some minor change requests. Let me know if you have any doubt.

2020-03-31 23:02 UTC, isabelcosta commented on app/messages.py
> +USER_NOT_INVOLVED_IN_MENTORSHIP_RELATION = {
Instead of creating this new message, you can use this one that already exists `USER_NOT_INVOLVED_IN_THIS_MENTOR_RELATION `
Line 136: https://github.com/anitab-org/mentorship-backend/pull/520/files#diff-3a3e7c840a0d5a8e57c891b68ff5a3b5R136

So you can remove these 3 new lines of code and just reuse the above variable

2020-03-31 23:02 UTC, isabelcosta commented on app/api/dao/task.py
> +        if (relation.mentor_id != user_id) & (relation.mentee_id != user_id):
```suggestion
        if (relation.mentor_id != user_id) and (relation.mentee_id != user_id):
```

2020-03-31 23:02 UTC, isabelcosta commented on tests/tasks/test_dao_create_task.py
> +    def test_create_task_with_user_not_involved_in_membership(self):
well done with this test 👏

2020-03-31 23:02 UTC, isabelcosta commented on tests/tasks/test_dao_create_task.py
> +    def test_create_task_with_user_not_involved_in_membership(self):
```suggestion
    def test_create_task_with_user_not_involved_in_mentorship(self):
```

2020-04-02 10:25 UTC, Ashokrayal commented on tests/tasks/test_dao_create_task.py
> +    def test_create_task_with_user_not_involved_in_membership(self):
thank you :)

2020-04-02 10:33 UTC, Ashokrayal commented on app/messages.py
> +USER_NOT_INVOLVED_IN_MENTORSHIP_RELATION = {
Done. Thank you for pointing out such minor details :)

2020-04-02 11:58 UTC, Ashokrayal commented
Hi @isabelcosta ,

I have made all the changes suggested by you.

2020-04-05 23:06 UTC, isabelcosta approved these changes

2020-04-17 11:38 UTC, Ashokrayal commented
@isabelcosta Can you please get someone to merge it?

2020-04-17 18:02 UTC, isabelcosta commented
@Ashokrayal I approved it from the point of view of the code, now we would like for someone to test the code locally and say if the behavior is actually correct. Once that is done, I can merge :)

2020-04-18 11:19 UTC, faznan3nazer reviewed
![WhatsApp Image 2020-04-18 at 4 29 51 PM](https://user-images.githubusercontent.com/50888936/79636274-27bc0d80-8194-11ea-8c32-1846d7ff7026.jpeg)

Locally tested and seeing expected result

2020-04-18 12:19 UTC, isabelcosta commented
@faznan3nazer thank you so much for testing! 👏 
I just tested, to test my new local dev environment and I got the same result as you 

![image](https://user-images.githubusercontent.com/11148726/79637378-16b0d380-8177-11ea-96ef-202c17908e5c.png)

Thank you @Ashokrayal for your contribution 🎉 This is great!

2020-04-18 12:21 UTC, merged

2020-04-18 16:20 UTC, Ashokrayal commented
Thanks @isabelcosta and @faznan3nazer