Add to List Users API the ability to filter users who need or want to provide mentoring (issue # 424)
anitab-org/mentorship-backend pull request #535
Opened 2020-04-09 15:10 UTC by lmcicat

### Description
As a member of the app,
I need be able to filter other members for their availability,
so that I can choose the member I want to create a mentorship relation with.

APIs used to fetch Users, don't have an option to filter users by need_mentoring and available_to_mentor attributes.

Fixes # 424

### Type of Change:

- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
We created more unit tests in the tests/users/test_api_list_users.py. You can run these tests by following this guideline: https://github.com/anitab-org/mentorship-backend#run-tests.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-04-25 19:27 UTC, faznan3nazer reviewed
![1](https://user-images.githubusercontent.com/50888936/80288864-8ff08d80-8758-11ea-931c-5496909ddf67.jpeg)
![2](https://user-images.githubusercontent.com/50888936/80288866-91ba5100-8758-11ea-835c-0f30ea241d96.jpeg)
![3](https://user-images.githubusercontent.com/50888936/80288867-9252e780-8758-11ea-9797-d15b831607d1.jpeg)
![4](https://user-images.githubusercontent.com/50888936/80288868-92eb7e00-8758-11ea-8d18-5292ffa30204.jpeg)
![5](https://user-images.githubusercontent.com/50888936/80288869-93841480-8758-11ea-8139-9683585cb52f.jpeg)
![6](https://user-images.githubusercontent.com/50888936/80288870-941cab00-8758-11ea-9849-747639b52af8.jpeg)
![7](https://user-images.githubusercontent.com/50888936/80288871-94b54180-8758-11ea-98d3-c1a1b02721b5.jpeg)
![8](https://user-images.githubusercontent.com/50888936/80288872-954dd800-8758-11ea-9bca-6027d7a3192e.jpeg)
![9](https://user-images.githubusercontent.com/50888936/80288873-95e66e80-8758-11ea-92ed-c4b593bc2149.jpeg)
![10](https://user-images.githubusercontent.com/50888936/80288875-967f0500-8758-11ea-8726-10aceebb897c.jpeg)
![11](https://user-images.githubusercontent.com/50888936/80288876-97179b80-8758-11ea-9b24-362072fb30a3.jpeg)
![12](https://user-images.githubusercontent.com/50888936/80288878-97b03200-8758-11ea-85af-d4f6f8ec8eb6.jpeg)
![13](https://user-images.githubusercontent.com/50888936/80288880-9848c880-8758-11ea-8e32-21de7e052ef4.jpeg)
![14](https://user-images.githubusercontent.com/50888936/80288881-98e15f00-8758-11ea-8517-bb9d5deff41e.jpeg)
![15](https://user-images.githubusercontent.com/50888936/80288883-9979f580-8758-11ea-8732-4432f082370b.jpeg)
![16](https://user-images.githubusercontent.com/50888936/80288884-9a128c00-8758-11ea-8e37-1b4d659eab15.jpeg)
![18](https://user-images.githubusercontent.com/50888936/80288886-9aab2280-8758-11ea-9401-8ffd1da8b1c6.jpeg)
![19](https://user-images.githubusercontent.com/50888936/80288888-9b43b900-8758-11ea-8c3e-2648aa97aac3.jpeg)
![20](https://user-images.githubusercontent.com/50888936/80288889-9bdc4f80-8758-11ea-9fc6-f10667d2b290.jpeg)
![21](https://user-images.githubusercontent.com/50888936/80288890-9c74e600-8758-11ea-9a70-a0c9010a30aa.jpeg)
![22](https://user-images.githubusercontent.com/50888936/80288891-9d0d7c80-8758-11ea-9f73-076386b9fd18.jpeg)
![23](https://user-images.githubusercontent.com/50888936/80288892-9da61300-8758-11ea-8eb1-c9de29c4a91c.jpeg)
![24](https://user-images.githubusercontent.com/50888936/80288893-9ed74000-8758-11ea-9f5c-ec79433b3617.jpeg)
Tested the feature locally.

2020-04-25 21:31 UTC, lmcicat commented
Just realized I never updated the `list_users` docs to include the new parameters. pushed up the change now.

2020-04-27 14:22 UTC, foongminwong approved these changes
Great job @lmcicat and @brianguo98!!! I apologize for the late review, just want to make sure the PR is tested correctly before merging..
@isabelcosta here're the GIFs of before (original) vs after pr535

**Before pr535 - `Original`**
![before_pr535](https://user-images.githubusercontent.com/23441795/80382311-c2d57700-8867-11ea-8af0-4eaf409f33e1.gif)

**After pr535 - `GET /users`**
![after_pr535_GETusers](https://user-images.githubusercontent.com/23441795/80382720-3aa3a180-8868-11ea-9d91-dc06c3d06cde.gif)

**After pr535 - `GET /users/verified`**
![after_pr535_GETusersverified](https://user-images.githubusercontent.com/23441795/80382728-3d9e9200-8868-11ea-8bfb-920b66ef1e9c.gif)

2020-04-27 14:26 UTC, foongminwong reviewed
@isabelcosta I wasn't able to run the unit test `test_api_list_users.py` since I'm still having issue that I'm tryign to fix [here](https://anitab-org.zulipchat.com/#narrow/stream/216325-quality-assurance/topic/Testing.20Error/near/195101602)

2020-04-29 17:33 UTC, isabelcosta commented
@faznan3nazer @foongminwong thank you sooooo much for your QA work here! it is super duper helpful :) 🎉

2020-05-05 18:00 UTC, isabelcosta reviewed
I ran the code locally, and I tested the following use cases:
1. invalid `available_to_mentor` value set to "urusla" which is not a boolean

![image](https://user-images.githubusercontent.com/11148726/81099229-7abaf200-8f02-11ea-9379-e1ce9bbbfab6.png)

2020-05-05 18:28 UTC, lmcicat commented
@isabelcosta what do you want to happen if true/false aren't passed in?

2020-08-15 17:36 UTC, SanketDG requested changes
I think keeping a flag value as string is going to cause a lot of problems with random data and tests, so a better way of enforcing this would be to use boolean as the data type strictly in all places with the `false` value as default!

Now for when we will consume this API on the client side, we can just set default values there!

2020-08-23 22:57 UTC, isabelcosta commented
I'm sorry for the delay in my response @lmcicat .
Would you be willing to address @SanketDG 's comment to improve this PR and fix the merge conflicts?
If not, that's ok we can leave this to another contributor, if yes, we can wait.

2020-08-24 13:28 UTC, lmcicat commented
Sorry for the delayed response @isabelcosta @SanketDG . I am pretty busy with work at the moment, but I can work on it come Friday / the weekend. If that isn't soon enough for you, feel free to let other contributors work on it :)

2020-08-24 17:48 UTC, isabelcosta commented
no problem @lmcicat ;) It's ok we can wait

2020-09-01 18:46 UTC, lmcicat commented
hi @isabelcosta I'm sorry about this, but I am much more busy with work than I expected. If you could open this up to others to grab, that would probably be a good idea.

2020-09-03 20:54 UTC, isabelcosta commented
@lmcicat no worries at all, I will open to other contributors, if no one picks up and you want to contribute in the future, feel free to do so! Thank you for your patience and work I really really appreciate it. 🙌  This can help a future contributor 🤗 

Good luck with your work!

2020-09-03 20:54 UTC, closed without merging