feat : getting user_name and photo_url in json returned after get req…
anitab-org/mentorship-backend pull request #550
Opened 2020-04-23 11:34 UTC by jotharman

feat : getting user_name and photo_url in json returned after get request for listing out comments

### Description
user comment providing user_name of the user along with profile picture
Fixes #444 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Resolved the tests which were giving error due to changes in the code.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] existing unit tests pass locally with my changes

2021-03-20 05:59 UTC, epicadk requested changes

2021-03-20 05:59 UTC, epicadk commented on app/api/dao/task_comment.py
> -    def get_all_task_comments_by_task_id(user_id, task_id, relation_id):
Please solve the merge conflicts.

2021-03-27 12:10 UTC, vj-codes commented
@jotharman any updates?

2021-04-07 17:34 UTC, vj-codes commented
@jotharman closing this PR due to inactivity
Thank you for your contribution :)

2021-04-07 17:34 UTC, closed without merging