refactor: HTTP error codes POST /mentorship_relation/send_request
anitab-org/mentorship-backend pull request #649
Opened 2020-06-19 15:02 UTC by satya7289

### Description

Refactor HTTP status code from 200->201(ok->created) @ POST /mentorship_relation/send_request

Fixes #626

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

![Screenshot from 2020-06-19 20-31-04](https://user-images.githubusercontent.com/35588980/85146985-d26fab80-b26b-11ea-8989-d2304079c61e.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-06-20 11:45 UTC, isabelcosta requested changes
@satya7289 i left a little change request, after that is done, I would be more than happy to approve it 💪

2020-06-20 11:45 UTC, isabelcosta commented on tests/mentorship_relation/test_api_send_request.py
> +        self.assertEqual(201, actual_response.status_code)
Can you use `HTTPStatus.CREATED` instead of 201?

2020-06-20 23:07 UTC, isabelcosta approved these changes
Looks good @satya7289 💯 
@anitab-org/coding-team could you please help reviewing this :)

2020-06-21 02:32 UTC, robotjellyzone approved these changes
LGTM, 👍 @satya7289

2020-06-22 22:29 UTC, isabelcosta commented
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Sent a request from Catarina to another user_  
    _Screenshot/gif_:  
![send request proof of success on Swagger UI](https://user-images.githubusercontent.com/11148726/85341243-9d6b8f00-b4df-11ea-89a7-90338fa6cbf6.png)
    _Expected Result_:  Get 201 CREATED as HTTP status code
    _Actual Result_: Got 201 as HTTP status code
    
3. Additional testcases covered:

N/A
    
4. Additional Comments: Tested on the deployment environment of this PR https://ms-backend-review-pr-649.herokuapp.com/ 🎉 

5. Status of PR Changed to: Ready to Merge.

2020-06-22 22:30 UTC, isabelcosta commented
@robotjellyzone thank you so much for your review!
Thank you for your contribution @satya7289 🙌

2020-06-22 22:30 UTC, merged