fix: refractor HTTP error codes PUT/mentorship_relation/{request_id}/reject
anitab-org/mentorship-backend pull request #671
Opened 2020-07-15 15:16 UTC by vj-codes

### Description
Changed 400: Bad Request to 403:FORBIDDEN,
 if the request state is not pending state, the request is sent to themselves, the request is for uninvolved mentor relation.

Fixes #628

### Type of Change:

- Code
- Documentation

### How Has This Been Tested?
![IMG_20200715_204309](https://user-images.githubusercontent.com/60894542/87562701-ed530580-c6db-11ea-8341-01aab0b4967a.jpg)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

2020-07-15 15:20 UTC, vj-codes commented
@isabelcosta @SanketDG @mtreacy002 I'm new to backend so couldn't exactly create a test for this PR.Can any of you help?

2020-07-15 22:56 UTC, isabelcosta requested changes
@vj-codes you started great! There is just a few things missing to complete this.

You also have to change the actual response returns instead of just the swagger documentation.
Here's 1 example: https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/dao/mentorship_relation.py#L248 then you have 2 more lines below you have to change.

Let me know if any of this is confusing to you 😉

2020-07-17 12:05 UTC, vj-codes commented
> @vj-codes you started great! There is just a few things missing to complete this.
> 
> You also have to change the actual response returns instead of just the swagger documentation.
> Here's 1 example: https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/dao/mentorship_relation.py#L248 then you have 2 more lines below you have to change.
> 
> Let me know if any of this is confusing to you 😉

Got it!I have changed them too.Please review again whenever you are free:)

2020-07-17 13:07 UTC, vj-codes commented
@isabelcosta Should I change HTTP code in selected line of  [test1]( https://github.com/anitab-org/mentorship-backend/blob/develop/tests/mentorship_relation/test_dao_reject_mentorship_request.py#L70) and [test2]( https://github.com/anitab-org/mentorship-backend/blob/develop/tests/mentorship_relation/test_dao_reject_mentorship_request.py#L95) so the build from gh actions is completed successfully?

2020-07-18 14:02 UTC, isabelcosta commented
Yes @vj-codes tests should be fixed to use the correct codes :)

2020-07-18 14:42 UTC, vj-codes commented
@isabelcosta after 5 tries I managed to get  the build successful hahaha.Can you review it again?Now I get how backend works(almost) !

2020-07-18 17:01 UTC, isabelcosta commented
> Now I get how backend works(almost) !

This is amazing @vj-codes I am so happy you are learning here through your contribution!

2020-07-18 17:02 UTC, isabelcosta approved these changes
Amazing @vj-codes ! So glad you learned things along the way with your contribution!
Thank you so much for this 🎉

2020-07-18 17:12 UTC, isabelcosta commented
I just need another review to merge this :)

2020-07-18 20:19 UTC, SanketDG approved these changes
LGTM!

2020-07-18 20:24 UTC, vj-codes commented
> Amazing @vj-codes ! So glad you learned things along the way with your contribution!
> Thank you so much for this 🎉

Thank you too , learning a new thing from every issue and PR :)
@isabelcosta

2020-07-18 21:06 UTC, rpattath commented
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_ : Mentee rejects a request that is not in pending state
    _Screenshot/gif_:  
![Screenshot from 2020-07-18 16-54-56](https://user-images.githubusercontent.com/26095715/87861916-e36a1600-c918-11ea-8207-ac9c01e47bf8.png)

    _Expected Result_:  403 Error - This mentorship relation is not in the pending state
    _Actual Result_: Same as above
  * _Test2 Description_ : Mentee rejects a request that the person is not involved in
    _Screenshot/gif_:  
![Screenshot from 2020-07-18 16-59-37](https://user-images.githubusercontent.com/26095715/87861926-fbda3080-c918-11ea-98de-18ef800fab99.png)

    _Expected Result_:  403 Error - You cannot reject a mentorship relation where you are not involved.
    _Actual Result_:  Same as above
 * _Test2 Description_ : Mentee rejects a request that the person themself.
    _Screenshot/gif_:  
![Screenshot from 2020-07-18 16-54-12](https://user-images.githubusercontent.com/26095715/87861905-cb929200-c918-11ea-938e-298cdcf4dc65.png)

    _Expected Result_:  403 Error - You cannot reject a mentorship request sent by yourself.
    _Actual Result_:  Same as above
    ...  
    
3. Additional testcases covered: n/a
    
4. Additional Comments:

5. Status of PR Changed to: Ready to Merge.

2020-07-18 21:08 UTC, isabelcosta commented
Thank you sooo much for testing this so quick 💪 @rpattath 👏

2020-07-18 21:09 UTC, merged