Fix:updating an user with empty username and name gives an error message
anitab-org/mentorship-backend pull request #695
Opened 2020-07-21 10:58 UTC by rashikaqureshi

while updating user details if the username or name is empty. then added an error message. 

Fixes # [ISSUE]
Tested these scenarios.

![Screenshot 2020-07-21 14 19 01](https://user-images.githubusercontent.com/19991522/88045759-a7c78a00-cb6c-11ea-947d-dc8f47f3b0e0.png)
![Screenshot 2020-07-21 16 20 42](https://user-images.githubusercontent.com/19991522/88046916-6506b180-cb6e-11ea-8fd4-c96a48b394ed.png)
![Screenshot 2020-07-21 14 18 43](https://user-images.githubusercontent.com/19991522/88046967-794aae80-cb6e-11ea-8a78-df0af95512c5.png)
![Screenshot 2020-07-21 14 18 30](https://user-images.githubusercontent.com/19991522/88047096-b31bb500-cb6e-11ea-8550-f95c02bfd60f.png)
![Screenshot 2020-07-21 14 19 59](https://user-images.githubusercontent.com/19991522/88047200-de060900-cb6e-11ea-9eb5-8c99e2cbe712.png)
![Screenshot 2020-07-21 16 27 17](https://user-images.githubusercontent.com/19991522/88047433-3c32ec00-cb6f-11ea-8f98-d99d3c38ab3d.png)

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-08-13 08:34 UTC, vj-codes commented
@anitab-org/coding-team This PR needs review. Thanks!

2020-08-31 15:14 UTC, SanketDG requested changes
Some basic style changes

2020-08-31 15:14 UTC, SanketDG commented on app/api/dao/user.py
> +                return messages.NAME_FIELD_IS_MISSING,HTTPStatus.OK
I'd rewrite this as:

```python
try:
    user.name = data["name"]
except KeyError:
    return ....
```

2020-12-22 16:17 UTC, devkapilbansal commented
@rashikaqureshi please do the changes as requested

2020-12-31 20:41 UTC, vj-codes commented
@rashikaqureshi Closing the PR due to no update response and inactivity.
Thank you for your contribution 🎉

2020-12-31 20:41 UTC, closed without merging