Code : issue636 - Fix - refactor HTTP error codes GET /mentorship_relation/{r…
anitab-org/mentorship-backend pull request #698
Opened 2020-07-24 02:49 UTC by Ritika5901234

…equest_id}/task/{task_id}/comments

### Description

Fixes # 636

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

2020-07-24 10:45 UTC, vj-codes requested changes
@Ritika5901234 Any specific reason for changing the f-string format ?I don't think  that was supposed to be changed along with HTTP status.

2020-08-21 01:12 UTC, isabelcosta requested changes
We just need you to change one little thing, I wrote in my comment :) Other than that, your PR is ready to go :)
Thank you for contributing to this 🎉

2020-08-21 01:12 UTC, isabelcosta commented on app/api/resources/mentorship_relation.py
> +            f"{messages.TASK_DOES_NOT_EXIST['message']}"
@Ritika5901234 could you please follow @vj-codes suggestion? The `['message']` would not make the documentation on Swagger UI accurate.

2021-02-21 11:46 UTC, vj-codes commented
Closing this due to inactivity

2021-02-21 11:46 UTC, closed without merging