Create api_extension(update)
anitab-org/mentorship-backend pull request #725
Opened 2020-08-16 14:21 UTC by 19-pragya

### Description

Fixes # [ISSUE]

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-08-16 20:39 UTC, vj-codes requested changes
@19-pragya why is everything from title repeated twice?Just remove it once, leave a line after `from flask_restx import Api` and shift the lines you added below the Android client line.
Just these minor changes and then , you're done!
Great work on your first PR here btw:)

2020-08-17 06:15 UTC, 19-pragya commented
@vj-codes  please check now!

2020-08-17 07:45 UTC, vj-codes requested changes
Great process , sorry but title,version and description, docs is still repeated twice.And shift line flutter and ios line just below line 9 .
Please change this last time and then you're done @19-pragya  👍

2020-08-17 09:30 UTC, 19-pragya commented
@vj-codes please check
https://github.com/anitab-org/mentorship-backend/pull/725/files

2020-08-22 07:05 UTC, anna4j approved these changes

2020-08-22 07:09 UTC, anna4j commented
@19-pragya LGTM! Check out Open Source Hack:  https://anitab-org.github.io/events/open-source-hack/

@vj-codes Should I close this issue? Please review it

2020-08-22 07:15 UTC, vj-codes commented
@anna4j I was waiting for the author to shift the Flutter and ios lines to be shifted just below the Android one to maintain consistency. I mentioned it twice earlier so just waiting:)

2020-08-23 23:13 UTC, isabelcosta commented
@19-pragya I updated your PR description to include the link. Please take a look :)
Also, you need to fill in a little more information, even if this is a very small PR, its good if you show us how you tested, to help reviewers understand how they can also test your change, and check the checklist for what items you completed :)

2020-08-23 23:18 UTC, isabelcosta requested changes
@19-pragya thank you for working on this issue 🎉  this will really enhance the Swagger UI :)

I requested a change to make your contribution match what the issue is requesting, after that is done I am more than happy to approve!

2020-08-23 23:18 UTC, isabelcosta commented on api_extension(update)
> +    + "For ios client for the Mentorship System can be found here: https://github.com/anitab-org/mentorship-ios"
These 2 lines are correct :) but the file you put them on is not. You are creating a new file, when what its desired is to edit a specific file called `/app/api/api_extension.py` and this is where you have to add those 2 lines.

Line: https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/api_extension.py#L11

To test this change you have to run the project, so please follow the instructions on the README to do so, and then provide a screenshot of your successful change showing it :)

2021-02-21 11:49 UTC, vj-codes commented
Closing as flutter and ios have been added currently

2021-02-21 11:49 UTC, closed without merging