Added setup and run guide for windows and linux
anitab-org/mentorship-backend pull request #807
Opened 2020-09-01 08:04 UTC by Abjcodes

### Description

Updated README.md by adding setup guides for windows and linux users as part of OSH.

Fixes #781 

### Type of Change:

- Documentation

### How Has This Been Tested?

Updated and previewed README.md.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

2020-09-01 08:50 UTC, vj-codes requested changes
@Abjcodes congrats on your 1st contribution! Here are some updates-
If the .env.template is adapted acc to the user in .env file , there's no need to again export environment variables in step 4. Also the DB part if required should be adapted in .env file only .
Could you please update and then you are done!

2020-09-01 08:50 UTC, vj-codes reviewed
@Abjcodes What about windows?

2020-09-01 11:49 UTC, Abjcodes commented
@vj-codes Thank you for the fast response and review.
I believe I have added windows setup, which is a modified version of the original run app section, since it was already compatible in Windows.
If you may, could you please specify what should I add in step 4?

2020-09-01 12:17 UTC, PrashanthPuneriya requested changes
You need to update the Table of Contents. Also, as @vj-codes mentioned to state changes in step-4

2020-09-01 12:35 UTC, PrashanthPuneriya requested changes
Also, please make these changes :)

2020-09-01 12:35 UTC, PrashanthPuneriya commented on README.md
> +`$ virtualenv`
Change this line to `virtualenv venv`. So, that we don't deviate from the Windows setup instructions.

2020-09-01 12:35 UTC, PrashanthPuneriya commented on README.md
> +`$ source bin/activate`
Change this to `source venv/bin/activate`

2020-09-02 05:15 UTC, Abjcodes commented
@vj-codes @PrashanthPuneriya I have made necessary changes. Please review it and check for any errors.

2020-09-03 05:48 UTC, Abjcodes commented
@vj-codes @PrashanthPuneriya Can you review this ?

2020-09-03 06:59 UTC, vj-codes requested changes
@Abjcodes for windows please change `.\env\Scripts\activate` to  `venv\Scripts\activate` for command line part in readme

2020-09-03 08:06 UTC, PrashanthPuneriya requested changes
I think it's better if we replace line numbers 45 to 47 as follows:-
```
`source ./venv/Scripts/activate` for Git Bash Users
`.\venv\Scripts\activate` for Windows Command Line Users
```
This is short and simple. What do you think @vj-codes @Abjcodes ?
Also, please verify whether the command mentioned above is right or wrong :)

2020-09-03 08:10 UTC, vj-codes commented
@PrashanthPuneriya I am working on windows and  the `.` should  not be there , just `venv\Scripts\activate`

2020-09-03 12:01 UTC, Abjcodes commented
@vj-codes @PrashanthPuneriya I have edited step 2 and removed '.' since it is also possible to navigate without using '.' Please check it and tell me if any further changes are required.

2020-09-03 12:09 UTC, vj-codes requested changes
@Abjcodes great!
just a minor change - no `\`  before cmd one just `venv\Scripts\activate` for cmd users and then your're done!

2020-09-03 12:16 UTC, Abjcodes commented
@vj-codes Sure. I have removed it. You can check it now.

2020-09-03 12:17 UTC, vj-codes submitted a review, later dismissed
LGTM!
@Abjcodes congrats on your first contribution in this repo 🎉

2020-09-03 13:20 UTC, PrashanthPuneriya reviewed
Everything is fine but, can you please squash the commits into one and follow this [commit style](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide) ?

2020-09-03 14:06 UTC, Abjcodes commented
@PrashanthPuneriya I have squashed the commits. Is there any more changes?

2020-09-04 10:59 UTC, PrashanthPuneriya submitted a review, later dismissed
LGTM :) Thanks for your contribution!
The latest commit message is okay for now but, make sure that you include `type: ...` instead of `author: ...` next time.

2020-09-04 11:44 UTC, keshakaneria submitted a review, later dismissed
Seems perfect after the suggested changes done! Well done @Abjcodes  👍

2020-09-04 11:48 UTC, gaurivn approved these changes, later dismissed
Great work, thank you

2020-09-04 23:43 UTC, isabelcosta requested changes
@Abjcodes your guide is very clear, I just left some minor formatting change requests to make the document consistent in the way commands are displayed.
This is almost done ;)

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +4. Make sure you create `.env` using `.env.template` and update the values of corresponding environment variables. Make sure you exported the following [environment variables](docs/environment-variab
```suggestion
4. Make sure you create `.env` using `.env.template` and update the values of corresponding environment variables. Make sure you exported the following [environment variables](docs/environment-variables.md) if you didn't adapt `.env.template` in the `.env` file:
```

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +$ flask run
```suggestion
export FLASK_APP=run.py
flask run
```
Removing those "$" for consistency

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +5. Run the app:
```suggestion
5. Run the app with `python run.py` or:
```
I would say this because `python run.py` still applies on Linux environments

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +`$ virtualenv venv`
```suggestion
`virtualenv venv`
```
for consistency, and some beginners may not understand that "$" is not part of the command to be run on terminal

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +`$ source venv/bin/activate`
```suggestion
`source venv/bin/activate`
```

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +Use: `$ printenv` to print the environment variables and check all configurations.
```suggestion
Use `printenv` to print the environment variables and check all configurations.
```

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +$ deactivate
```suggestion
deactivate
```

2020-09-04 23:43 UTC, isabelcosta commented on README.md
> +$ source deactivate
```suggestion
source deactivate
```

2020-09-05 16:24 UTC, Abjcodes commented
@isabelcosta Sure. I have made the requested changes. Please check it.

2020-09-05 23:40 UTC, gaurivn reviewed
[This](https://codecov.io/gh/anitab-org/mentorship-backend/pull/807/changes) might be the reason the codecov report gave a failed check...same issue with a PR I had sent some time ago, will check on it and get back here. Otherwise, everything is good, thank you.

2020-09-06 14:41 UTC, isabelcosta approved these changes
Looks good @Abjcodes 🎉

2020-09-06 14:44 UTC, vj-codes approved these changes
LGTM 🎉

2020-09-06 14:48 UTC, merged