Update
anitab-org/mentorship-backend pull request #838
Opened 2020-09-04 14:46 UTC by Anmollenka

### Description

End Date field is added.

Fixes # 616

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

End field has been added and  can be seen under desciption of error messages.

![Screenshot (952)](https://user-images.githubusercontent.com/48198809/92252047-56d8de80-eeeb-11ea-809c-62c89477e019.png)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

2020-09-05 13:17 UTC, Anmollenka commented
#616

2020-09-17 14:41 UTC, Anmollenka commented
@darecoder please review my pull request.

2020-09-17 15:24 UTC, SanketDG submitted a review, later dismissed
LGTM

2020-09-17 15:41 UTC, darecoder commented
Nice work @Anmollenka.

2020-09-17 16:11 UTC, Anmollenka commented
Thank You

2020-10-24 23:45 UTC, isabelcosta commented on .env.template
> -MOCK_EMAIL = <True-or-False>
can you remove this change as this is not related to the issue?

2020-10-25 02:33 UTC, Anmollenka commented
Ok @isabelcosta I will make the required changes.

2020-10-25 05:47 UTC, Anmollenka commented
@isabelcosta I tried removing that file but when I am trying to recommit it's getting merged with  commits of other people .Can you help me out.Thank You.

2020-10-25 05:51 UTC, Anmollenka commented
Shall I create another pull request for this?

2020-10-25 12:18 UTC, isabelcosta commented
@Anmollenka this is because you used the `develop` branch for development. Can you search for a bit, how you can update your fork's `develop` branch. That will probably prompt the merge commit, which is fine :)

Let me know if you struggle with it. If you struggle, we can consider creating a new PR, with a different branch. We ask in the CONTRIBUTING.md that you create a new branch before making your changes because this avoids that you run into this kind of problem :)

2020-10-26 08:06 UTC, Anmollenka commented
@isabelcosta I have made the required changes.Please review it.Thank You.

2020-10-28 00:03 UTC, isabelcosta requested changes
can you please "undelete" the `.env.template` file? you are almost there ;). Then I can approve & merge @Anmollenka

2020-10-28 13:11 UTC, Anmollenka commented
@isabelcosta I have removed the `.env.template` as it was not required for this issue.Is that okay??Please review my pull request.

2020-11-04 19:51 UTC, vj-codes commented
@devkapilbansal @SanketDG @isabelcosta hey this PR is from develop branch , although it can merged is it a good practice to do so ?

2020-11-05 03:28 UTC, devkapilbansal commented
@Anmollenka you should always make a new branch first before creating a pull request. 
@vj-codes I don't think there is any problem if this PR is merged

2020-12-22 20:00 UTC, isabelcosta approved these changes, later dismissed
Great work @Anmollenka 👏 🎉 
Thank you for your contribution!

2020-12-22 20:01 UTC, isabelcosta commented
@Anmollenka can you please fix the merge conflicts, after that ping me and then I can approve again.
cc @devkapilbansal @vj-codes

2020-12-23 10:39 UTC, devkapilbansal commented
@Anmollenka some tests are failing. Can you please look into that too

2020-12-23 10:40 UTC, Anmollenka commented
> @Anmollenka some tests are failing. Can you please look into that too

Yes,I am working on it.After that I will suash the commits.

2020-12-23 12:52 UTC, isabelcosta commented on app/api/resources/mentorship_relation.py
> +            messages.END_DATE_FIELD_IS_MISSING,
I think you have to add an extra `\n%s` in line 42 @Anmollenka :)

2020-12-26 20:13 UTC, devkapilbansal commented
@isabelcosta the problem may not be due to these pull requests but due to a bug in the develop branch itself. The same tests are failing in other updated PRs too

2020-12-27 21:42 UTC, isabelcosta commented
@Anmollenka can you please update your branch with latest changes from the `develop` branch? These might fix the issues you are having here with tests.
cc @devkapilbansal

2021-01-09 05:36 UTC, Anmollenka commented
@devkapilbansal Can you please review my pull request

2021-01-09 05:36 UTC, Anmollenka commented
@devkapilbansal Can you please review my pull request.

2021-01-11 20:17 UTC, devkapilbansal approved these changes
LGTM :+1:

2021-01-11 20:27 UTC, devkapilbansal commented
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  End Date Field check
    _Screenshot/gif_:  
![test_branch](https://user-images.githubusercontent.com/42766576/104234421-6360db00-5479-11eb-96e4-008cad53b9cf.png)

    _Expected Result_:  `End date field is missing` should be listed in error messages
    _Actual Result_: Same as expected
 
3. Status of PR Changed to: Ready to Merge.

2021-01-11 20:27 UTC, devkapilbansal commented
@vj-codes @isabelcosta Can you please re-review this pull request?

2021-01-24 03:11 UTC, isabelcosta approved these changes
Great work @Anmollenka 👏 
Thank you so much for your contribution!

2021-01-24 03:12 UTC, merged