Docs: Added a table in quality-assurance-test-cases.md
anitab-org/mentorship-backend pull request #849
Opened 2020-09-08 17:37 UTC by pallavisavant

**Description**

Added table in quality-assurance-test-cases.md which includes all the required test cases for email confirmation API

Fixes #471

**Type of Change:**

- 1. Documentation

 **Checklist:**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

2020-09-08 20:18 UTC, vj-codes requested changes
@pallavisavant congrats on your first contribution to the repo 🎉 
Capitalize letter` v` in test case 2 and 3 and
Please could you add screenshots of all or failed tests atleast in the PR template (not in docs)
It will help to verify and make the tests pass later.
Then you are done:)

2020-09-08 21:24 UTC, pallavisavant commented
@vj-codes included respective changes.....pls do review..Thank you.

2020-09-08 21:27 UTC, vj-codes approved these changes
LGTM 🎉

2020-09-12 23:26 UTC, isabelcosta commented on docs/quality-assurance-test-cases.md
> +| Verification token of already confirmed users account entered                                  | Success |
Interesting 🤔  If the user is already created the API should not do anything. I guess that counts as a success for now :) @pallavisavant great thought

2020-09-12 23:27 UTC, isabelcosta commented on docs/quality-assurance-test-cases.md
> +| Verification token of already confirmed users account entered                                  | Success |
I guess here the expected behavior should be a message with saying the user is already confirmed. All in all, i think this is fine :)

2020-09-12 23:27 UTC, isabelcosta approved these changes
Great work @pallavisavant 👏 
Thank you for your contribution! 🎉

2020-09-12 23:29 UTC, merged