Fix Delete relation when the user did not create the request #771
anitab-org/mentorship-backend pull request #857
Opened 2020-09-09 17:57 UTC by dowenrei

### Description
Existing code checks whether the relationship is in pending state before checking whether the relationship belongs to the user who created the request, this will throw a wrong error message if the relationship is in the accepted state and another user (who does not own this relationship) tries to delete this relationship. Thus, adjusting the sequence of the code will first check whether the relationship belongs to the rightful user, which results in the correct error message.   

When 
Fixes # 771 
Fix wrong Error message response when user deletes a relationship that is not created by them.

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

I have tested this by reproducing the behaviour stated by @rpattath.

### Checklist:

- [/] My PR follows the style guidelines of this project
- [/] I have performed a self-review of my own code or materials
- [/] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**

- [ /] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [/] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-09-12 23:21 UTC, rpattath approved these changes
LGTM for OSH

2020-09-22 20:08 UTC, isabelcosta requested changes
Great contribution!
@dowenrei could you please add a unit test, that shows that your change works as it should?

2020-09-22 20:36 UTC, dowenrei commented
> Great contribution!
> @dowenrei could you please add a unit test, that shows that your change works as it should?

@isabelcosta Thank you. Do you mean adding screenshots of the successful implementation to my PR comments?

2020-09-22 23:06 UTC, isabelcosta commented
> > Great contribution!
> > @dowenrei could you please add a unit test, that shows that your change works as it should?
> 
> @isabelcosta Thank you. Do you mean adding screenshots of the successful implementation to my PR comments?

I mean writing a test that would fail if you have not made your change. That would pass, only now with your change. You can create the test here: https://github.com/anitab-org/mentorship-backend/blob/develop/tests/mentorship_relation/test_api_delete_request.py

Does that make sense @dowenrei ?

2020-09-25 16:24 UTC, dowenrei commented
> > > Great contribution!
> 
> > > @dowenrei could you please add a unit test, that shows that your change works as it should?
> 
> > 
> 
> > @isabelcosta Thank you. Do you mean adding screenshots of the successful implementation to my PR comments?
> 
> 
> 
> I mean writing a test that would fail if you have not made your change. That would pass, only now with your change. You can create the test here: https://github.com/anitab-org/mentorship-backend/blob/develop/tests/mentorship_relation/test_api_delete_request.py
> 
> 
> 
> Does that make sense @dowenrei ?

@isabelcosta Yes,understood. Will do it this weekend!

2020-11-04 20:19 UTC, vj-codes commented
@dowenrei hey any updates?

2020-11-30 19:12 UTC, vj-codes commented
@dowenrei hey any updates for changes requested ?

2021-02-18 18:18 UTC, vj-codes commented
@dowenrei I will close this PR and make the issue available due to inactivity.
Let us know if you would like to continue again and thank you for your contribution :)

2021-02-18 18:18 UTC, closed without merging