Fixed, searching based on both the username and name #745
anitab-org/mentorship-backend pull request #861
Opened 2020-09-10 16:38 UTC by codesankalp

Now the search function finds the mentor/mentee based on both username and name.

To solve this issue added a condition to search on basis of username when search on basis
of name is empty.

Tests: Manually tested by searching for user with the username and name

Fixes #745

checklist : 
- [x] Implemented searching on basis of username.

2020-09-10 17:40 UTC, codesankalp commented
@PrashanthPuneriya review it.

2020-09-10 19:51 UTC, SanketDG reviewed
Wondering whether we can do something using a standard [`or_`](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.or_)

2020-09-11 08:31 UTC, PrashanthPuneriya reviewed
> Wondering whether we can do something using a standard or_

Yes! Implementing within the prevs code logic would be better. Also, I think it is better if we use `AND operation instead of OR operation` because, it would show both the results of `username` and `name` instead of showing the results by `username` only when we don't find any user by `name`.

2020-09-11 12:32 UTC, codesankalp commented
@PrashanthPuneriya If we use `AND` operation then it will check for both username and name which results to return an empty list. But according to @SanketDG  idea using `OR` will be good and it's working also (tested by me).

2020-09-11 13:28 UTC, SanketDG submitted a review, later dismissed
Looks good, but I just have this feeling that an explcit `or_` is better than `|`

and yes `and` won't work because of obvious reasons :smile:

2020-09-11 14:31 UTC, codesankalp commented
So should i make the change with `or_` or `|` this is ok.
In documentation it is mentioned that both have the same functionality.
@SanketDG

2020-09-11 17:51 UTC, PrashanthPuneriya submitted a review, later dismissed
Good work @codesankalp!
Yes, I was wrong. I got confused with what OR, AND does and thus described OR operation in plain english 😅

2020-09-30 18:09 UTC, devkapilbansal approved these changes
LGTM

2020-10-28 19:44 UTC, devkapilbansal submitted a review, later dismissed
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Search for user with username 
    _Screenshot/gif_:  
![1st](https://user-images.githubusercontent.com/42766576/97487984-a71c6c00-1983-11eb-804e-fd593c7a12f2.png)

    _Expected Result_ are same as _Actual Result_

  * _Test2 Description_  Search for user with name
    _Screenshot/gif_:  
![2nd](https://user-images.githubusercontent.com/42766576/97488079-c4e9d100-1983-11eb-8c26-9551c2bd25f3.png)

     _Expected Result_ are same as _Actual Result_
    
3. Additional Comments: Run `python -m unittest discover tests` to ensure all test cases passed.

4. Status of PR can be Changed to: Ready to Merge.

2020-10-28 19:46 UTC, devkapilbansal commented
@vj-codes look in this PR too. This pull request has three approvals already but it has not been provided with any relevant label.

2020-10-28 19:47 UTC, vj-codes commented
Review , testing  ✔️ 
Adding label ready to merge

2020-12-16 23:21 UTC, isabelcosta requested changes
@codesankalp there are some merge conflicts due to other merges, could you please fix these here. And also, since you would be changing the code, could you please just add a small unit test that tests the feature you just fixed. A simple test that would fail if your wasn't in place.

2020-12-17 13:31 UTC, codesankalp commented on tests/tasks/test_api_list_tasks.py
> +            f"/mentorship_relation/{self.mentorship_relation_w_admin_user.id}" "/tasks",
the tests are not passing due to this and after reformatting the tests passed so the extra two files changed are `tests/tasks/test_api_list_tasks.py` and `tests/users/test_api_list_users.py`

2020-12-17 21:11 UTC, isabelcosta requested changes
@codesankalp I suggested a little style change, can you please address it. I can approve after. Thank you for creating a new test 👏

2020-12-17 21:11 UTC, isabelcosta commented on tests/tasks/test_api_list_tasks.py
> +            f"/mentorship_relation/{self.mentorship_relation_w_admin_user.id}" "/tasks",
```suggestion
            f"/mentorship_relation/{self.mentorship_relation_w_admin_user.id}/tasks",
```
can you do it like this? no need to break the string in this case :)

2020-12-17 21:11 UTC, isabelcosta commented on tests/tasks/test_api_list_tasks.py
> +            f"/mentorship_relation/{self.mentorship_relation_w_admin_user.id}" "/tasks",
```suggestion
            f"/mentorship_relation/{self.mentorship_relation_w_admin_user.id}/tasks",
```

2020-12-17 21:11 UTC, isabelcosta commented on tests/tasks/test_api_list_tasks.py
> +            f"/mentorship_relation/{self.mentorship_relation_w_admin_user.id}" "/tasks",
please replicate this change in all of the lines you changed to be like this

2020-12-20 23:29 UTC, isabelcosta approved these changes
💯 👏  Thank you for addressing the code review so well :)

2020-12-21 04:45 UTC, devkapilbansal approved these changes

2020-12-21 10:11 UTC, PrashanthPuneriya approved these changes

2020-12-21 19:55 UTC, isabelcosta commented
I will merge this PR since it was already tested here https://github.com/anitab-org/mentorship-backend/pull/861#pullrequestreview-519025127
Thank you so much for testing this @devkapilbansal 🙌 
Thank you for your contribution @codesankalp 👏

2020-12-21 19:56 UTC, merged