fixing get user_id issue
anitab-org/mentorship-backend pull request #884
Opened 2020-09-19 12:03 UTC by saikirankv

### Description

Fixes #702 

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-09-20 11:11 UTC, saikirankv commented
@isabelcosta @vj-codes can you review this PR?

2020-09-20 11:11 UTC, saikirankv commented
@SanketDG

2020-11-29 18:48 UTC, devkapilbansal commented on app/api/resources/user.py
> +        user_details = DAO.get_user(user_id)
Change the name back to requested_user

2020-11-29 18:48 UTC, devkapilbansal requested changes
Thanks @saikirankv for opening this.
But I can see that you change the variable name from `requested_user` to `user_details`. Is it intentional??
If not please revert it back.

Also, squash your commits into one

2020-11-30 10:38 UTC, saikirankv commented
@devkapilbansal I made the necessary changes, can you review again. Sorry I have deleted branch in my local, can please do squash and merge of this PR?

2020-11-30 11:08 UTC, devkapilbansal commented
> @devkapilbansal I made the necessary changes, can you review again. Sorry I have deleted branch in my local, can please do squash and merge of this PR?

You can fetch that branch again in local. I can't do the changes

2021-01-20 23:21 UTC, isabelcosta commented
@saikirankv can you please add information on PR description on how you tested this feature please? It can be helpful for a QA contributor to test your fix.
@NenadPantelic can you help reviewing this PR? (asking this because of your comment https://github.com/anitab-org/mentorship-backend/issues/702#issuecomment-761806453)
@devkapilbansal I can use "Squash and Merge" option in the end when this gets approved and tested/

2021-02-07 11:56 UTC, NenadPantelic commented
Tested locally:
1) unit tests pass (all of them)
2) tested through Swagger UI:
- Case 1: existing user (id = 2)
![image](https://user-images.githubusercontent.com/16724101/107145677-8fba2b00-6943-11eb-9dcb-d4f35a4a058f.png)
- Case 2: non-existing user (id=100)
![image](https://user-images.githubusercontent.com/16724101/107145694-a3fe2800-6943-11eb-82d9-d88ff3cd4fe5.png)

2021-02-07 11:59 UTC, NenadPantelic reviewed
The code is good. Please update your PR description and fill in the proper options.

2021-02-08 03:31 UTC, saikirankv commented
updated the PR description.

2021-02-10 18:45 UTC, NenadPantelic commented
> updated the PR description.

1) update the description
2) remove the things you don't need -> bugfix or new feature but not both
3) add screenshots from the Swagger with both scenarios - valid and invalid id etc.

2021-02-17 14:40 UTC, saikirankv commented
Updated the PR description, I think you already added the screenshots.

2021-02-21 09:43 UTC, NenadPantelic approved these changes
LGTM :+1:

2021-02-21 09:43 UTC, NenadPantelic commented
@vj-codes @devkapilbansal @Aaishpra @codesankalp Can someone review it?

2021-02-21 11:24 UTC, Aaishpra approved these changes
Great work @saikirankv 🎉 and thanks for the testing @NenadPantelic

2021-02-21 16:21 UTC, codesankalp commented
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done.

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  : Checking for user id that does not exist.
    _Screenshot/gif_:  
      User Table: 
     ![image](https://user-images.githubusercontent.com/56037184/108631146-9346c980-748e-11eb-92dd-d5dd7390364f.png)
      API Result: 
     ![oie_vJkAvZQvIR4Q](https://user-images.githubusercontent.com/56037184/108631213-b1142e80-748e-11eb-83d0-53e1568ca557.png)

    _Expected Result_:  404 Not Found.
    _Actual Result_: 404 Not Found.
    
3. Additional Comments:
Tested and reviewed. LGTM :tada: 

@isabelcosta @saikirankv

2021-02-21 19:53 UTC, isabelcosta approved these changes
Thank you for your contribution @saikirankv !

2021-02-21 19:54 UTC, merged