fix: error message for entering less than 4 characters for username
anitab-org/mentorship-backend pull request #888
Opened 2020-09-22 09:24 UTC by priyanshuone6

### Description
Fixed Error message for entering less than 4 characters for username under the update user profile and listed it in the responses.

Fixes #603 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

2020-09-22 16:19 UTC, SanketDG requested changes

2020-09-22 16:19 UTC, SanketDG commented on app/api/resources/user.py
> +)
Prettifying this makes this more unreadable :)

let's just go with the orignal style.

2020-09-22 16:48 UTC, priyanshuone6 commented
@SanketDG I have changed the style, please review it and let me know

2020-09-27 19:27 UTC, vj-codes requested changes
@priyanshuone6 can you please update the `how has this been tested part` .
I see the changes in HTTP.status Bad_request , but the response on top still shows longer than 4 and shorter than 26.
Maybe upload 2 screenshots one containing dummy data and second of responses.What say?

2020-09-28 03:49 UTC, priyanshuone6 commented
> @priyanshuone6 can you please update the `how has this been tested part` .
> I see the changes in HTTP.status Bad_request , but the response on top still shows longer than 4 and shorter than 26.
> Maybe upload 2 screenshots one containing dummy data and second of responses.What say?

I just added `messages.USERNAME_FIELD_IS_EMPTY` in `users_ns.response` and changed nothing except it.
Please have a look at the screenshots

![Screenshot (41)](https://user-images.githubusercontent.com/64051212/94388526-f72cc680-016a-11eb-86ce-588e2077dd50.png)
![Screenshot (42)](https://user-images.githubusercontent.com/64051212/94388528-f8f68a00-016a-11eb-9d4a-ba3899474e03.png)
![Screenshot (43)](https://user-images.githubusercontent.com/64051212/94388530-f98f2080-016a-11eb-835a-861f15aabe32.png)

2020-11-30 19:24 UTC, vj-codes requested changes
@priyanshuone6 hey please solve the merge conflicts.Thanks!

2021-02-01 10:09 UTC, Aaishpra requested changes
@priyanshuone6 can you remove the merge conflicts(as suggested above) and run black app/api/resources/user.py to reformat the code according to black standards so that the failing test can pass.

2021-02-17 07:11 UTC, epicadk commented
The tests are failing can you look into that @priyanshuone6

2021-02-17 11:19 UTC, closed without merging

2021-02-17 13:05 UTC, vj-codes commented
@priyanshuone6 you've closed this PR , let us know if you would like to continue on this issue orthwise it'll be marked as available for other contributors.

2021-02-17 13:38 UTC, priyanshuone6 commented
This PR is open for about 5 months, due to there are merge conflicts arising and I have solved them twice and no one's responding so I closed the PR.
You can mark the issue as open.