WIP :categorised mentorship relation ,task and comments
anitab-org/mentorship-backend pull request #893
Opened 2020-09-25 12:56 UTC by vj-codes

### Description
Categorised mentorship relation ,task and comments

Fixes #738

### Type of Change:

- Code
- User Interface
- Documentation

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

2020-09-27 19:13 UTC, vj-codes commented
@isabelcosta can you please look at this PR whenever you are free?Thanks!

2020-10-06 18:43 UTC, isabelcosta requested changes
Thank you for your contribution @vj-codes 💪 
I left some notes, although only one was critical piece missing.

Regarding the tests failing, I think at least one of them will be gone, after you address the change requests, other that failed at the API level (e.g.: 400 != 404 HTTP Code), those you will have to look at them one by one, and what changed in the functionality, because I think if this refactor is complete, there should not be failures at API tests level.

Ping me again, once you're done with the changes ;)

2020-10-06 18:43 UTC, isabelcosta commented on app/api/models/task_comment.py
> + api_namespace.models[task_comments_model.name] = task_comments_model
I think you are missing here the `def add_models_to_namespace(api_namespace):` line, since you are not defining the `api_namespace` anywhere.

2020-10-06 18:43 UTC, isabelcosta commented on app/api/resources/task.py
> +    description="Operations related to " " tasks in a mentorship relation " "between users",
```suggestion
    description="Operations related to tasks in a mentorship relation between users",
```
I know this part was copied and pasted, but could you please correct this?

2020-10-06 18:43 UTC, isabelcosta commented on app/api/resources/task.py
> +userDAO = UserDAO()
if these are not being used you can remove it ;)

2020-10-06 18:43 UTC, isabelcosta commented on app/api/resources/task_comments.py
> +
you can remove this if this is not being used, please check first before removing :)

2020-10-06 18:43 UTC, isabelcosta commented on app/api/resources/task_comments.py
> +    description="Operations related to " " task comments in a mentorship relation " "between users",
```suggestion
    description="Operations related to task comments in a mentorship relation between users",
```

2020-10-06 18:43 UTC, isabelcosta commented on app/api/dao/user.py
> +from app.api.models.task import (list_tasks_response_body)
```suggestion
from app.api.models.task import list_tasks_response_body
```

2020-10-06 18:43 UTC, isabelcosta commented on app/api/dao/user.py
> +from app.api.models.task import (list_tasks_response_body)
you don't need the parenthesis when you import only one thing :)

2020-10-14 12:14 UTC, nandini45 commented
@vj-codes  can you also recheck your travis build
recently i didn't contributed to the repository much so i dont know about the travis situation. i am lagging behind all updates and kindly make all  the changes Isabel told.

2021-01-10 18:38 UTC, vj-codes commented
Closing this PR and making the issue available again as I don't have the bandwidth to complete this anytime soon

2021-01-10 18:38 UTC, closed without merging