docs : added a file
anitab-org/mentorship-backend pull request #902
Opened 2020-09-28 16:20 UTC by Anmollenka

### Description

A solution for recommending mentees to a mentor.

Fixes #785 

### Type of Change:

- Code
- Outreach

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I have previewed the code in the editor.
![Screenshot (1038)](https://user-images.githubusercontent.com/48198809/94459067-786c7380-01d4-11eb-98a6-4e976756ff59.png)

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

2020-09-28 16:30 UTC, Anmollenka commented
@yashasvimisra2798 Can you please review my pull request.Thank You.

2020-09-29 05:12 UTC, yashasvimisra2798 reviewed
Is it only the programming languages or the fields as well?
eg: app development, computer vision etc

2020-09-29 05:30 UTC, Anmollenka commented
@yashasvimisra2798 I have taken only the programming languages as I was not sure of what are the different fields to be taken i.e what career developement topics in which mentoring are to be given.

2020-09-29 05:31 UTC, Anmollenka commented
Should I make any changes??

2020-09-30 10:18 UTC, yashasvimisra2798 submitted a review, later dismissed
It's ok with the programming languages. But having the skills would have been better.

2020-09-30 10:21 UTC, Anmollenka commented
Shall I make chan

> It's ok with the programming languages. But having the skills would have been better.

Shall I make the changes or is it okk??

2020-10-20 09:12 UTC, devkapilbansal requested changes
@Anmollenka please squash your commits into one. Also follow the commit guidelines. Feel free to change your pull request title too

2020-10-20 13:21 UTC, Anmollenka commented
@devkapilbansal I will make the required changes.

2020-10-21 08:18 UTC, Anmollenka commented
@devkapilbansal I have squashed the commits.

2020-10-21 08:30 UTC, Anmollenka commented
@devkapilbansal I tried squashing the commits into one but I don't know from where 2 commits are showing.Can you please help me with this.

2020-10-21 09:37 UTC, devkapilbansal commented
@Anmollenka follow these steps
```
At first fetch the new changes from develop branch
git remote add upstream https://github.com/anitab-org/mentorship-backend.git
git fetch upstream develop
git reset --soft upstream/develop
git commit
```

2020-10-21 10:48 UTC, Anmollenka commented
@devkapilbansal I have made the required changes.Please review it.Thank You.

2020-10-21 11:03 UTC, devkapilbansal requested changes
@Anmollenka it would be better if you upload your images to Github and use links instead. These binary files put unnecessary weights to the repository. 
Here is the guide on how to do that:
https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d

Also, feel free to edit the PR title to make it more descriptive

2020-10-21 11:55 UTC, Anmollenka commented
@devkapilbansal The images to explain my process through code in the markdown file.So I decided to upload the images in this repository.Do you want that I should upload  the images in some github repository of mine and then use a link.

2020-10-21 11:57 UTC, devkapilbansal commented
> @devkapilbansal The images to explain my process through code in the markdown file.So I decided to upload the images in this repository.Do you want that I should upload the images in some github repository of mine and then use a link.

Yes, it will not affect your markdown file too and reduce weight on repo at the same time

2020-10-24 06:14 UTC, Anmollenka commented
@devkapilbansal I have made the required changes.Please review it.Thank You.

2020-10-25 14:52 UTC, devkapilbansal requested changes
@Anmollenka some of your images are not visible in the markdown file. You can verify it manually by going to [its github link](https://github.com/Anmollenka/mentorship-backend/blob/new/docs/Recommendation.md).

2020-10-25 14:52 UTC, devkapilbansal commented on docs/Recommendation.md
> +<br>
@Anmollenka we can achieve same results by leaving the blank line too. No need to add <br>

2020-10-25 14:52 UTC, devkapilbansal commented on docs/Recommendation.md
> +
Why two blank lines here?One is enough here

2020-10-25 15:18 UTC, Anmollenka commented
@devkapilbansal I am able to preview it on my side.
![Screenshot (1098)](https://user-images.githubusercontent.com/48198809/97111168-4e3ea080-1703-11eb-8d0c-db24be8687ef.png)
I am not able to understand where I am going wrong.Thank You.

2020-10-25 15:20 UTC, Anmollenka commented
> @devkapilbansal I am able to preview it on my side.
> ![Screenshot (1098)](https://user-images.githubusercontent.com/48198809/97111168-4e3ea080-1703-11eb-8d0c-db24be8687ef.png)
> I am not able to understand where I am going wrong.

2020-10-25 15:47 UTC, devkapilbansal commented
@Anmollenka that `br` tags are making such differences. Use their alternatives

2020-10-26 04:33 UTC, Anmollenka commented
OK.I will make the changes

2020-10-26 13:27 UTC, Anmollenka commented
@devkapilbansal I have made the required changes.Please review it.

2020-10-28 09:54 UTC, devkapilbansal requested changes
@Anmollenka use any online tool to proofread the document and correct grammar/spelling error.
Grammarly can be good for that

2020-10-28 10:49 UTC, Anmollenka commented
> @Anmollenka use any online tool to proofread the document and correct grammar/spelling error.
> Grammarly can be good for that

@devkapilbansal I will keep this in mind.

2020-11-12 09:35 UTC, devkapilbansal requested changes
@Anmollenka can you please squash your commit in one

2021-01-28 18:37 UTC, devkapilbansal approved these changes

2021-04-12 08:51 UTC, vj-codes commented
@Anmollenka thank you for your contribution 
We will surely visit this PR when implementing the feature:)

2021-04-12 08:51 UTC, closed without merging