Change in Resources files to follow the same convention throughout
anitab-org/mentorship-backend pull request #905
Opened 2020-09-29 06:20 UTC by gitpurva

### Description

Same convention in resources files

Fixes #898 

### Type of Change:

- Code

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

2020-09-29 18:06 UTC, PrashanthPuneriya commented
@gitpurva You should always create a new branch on the top of develop branch while working on a new issue.
@devkapilbansal Do you know any workaround/fix ?

2020-09-29 19:11 UTC, devkapilbansal requested changes
@gitpurva you should rebase your commits on upstream/develop
Also, it would be good is you squash your commits in one. It's always better to use a single commit to solve an issue.
Here is the workflow you should follow:
```
git remote add upstream https://github.com/anitab-org/mentorship-backend.git
git rebase upstream/develop
git reset --soft HEAD~7
git commit --amend
```

2020-09-29 19:30 UTC, gitpurva commented
@devkapilbansal Ohkk.. I will do as said and will update the PR  .  Thank
You for your guidance:)

On Wed, Sep 30, 2020, 12:41 AM Kapil Bansal <notifications@github.com>
wrote:

> *@devkapilbansal* requested changes on this pull request.
>
> @gitpurva <https://github.com/gitpurva> you can rebase your commits on
> upstream/master
> Also, it would be good is you squash your commits in one. It's always
> better to use a single commit to solve an issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/anitab-org/mentorship-backend/pull/905#pullrequestreview-498800654>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALKVEGZ2X7NGPEUZOUN7IK3SIIWP3ANCNFSM4R5LUEHA>
> .
>

2020-10-01 07:54 UTC, PrashanthPuneriya commented
@gitpurva Any progress?

2020-10-15 19:38 UTC, vj-codes submitted a review, later dismissed
LGTM 🎉 
PR on separate branch ✔️

2020-10-15 19:39 UTC, vj-codes commented
@devkapilbansal review this again please!

2020-10-20 14:01 UTC, devkapilbansal commented
> @devkapilbansal review this again please!

@vj-codes I don't know whether the changes are as per convention or not and what are the conventions to follow. Pinging @PrashanthPuneriya to review

2020-10-20 15:02 UTC, PrashanthPuneriya commented on app/api/dao/mentorship_relation.py
>          """
This file shouldn't be part of the PR

2020-10-20 15:06 UTC, PrashanthPuneriya reviewed
`doc, route, response, parameters, expect, marshal_list_with` convention looks good to me. I am not sure about the convention tho it's just my thought.
Can we make all the above mentioned things appear above the class @gitpurva?

2020-10-24 14:49 UTC, gitpurva commented
I did not understand why the run test are failing as the same changes which I have commited earlier (which  passed all the test cases) but now it failed to do so inspite of the same changes which are pushed again:(
In the latest commits I haven't added anything extra in the file . I just placed all the methods above class to follow the convention.

2020-10-26 22:25 UTC, devkapilbansal commented
@gitpurva try to amend your previous commit instead of making a new commit for pull request. It will help you to better understand the changes and which change might be causing build to fail. Also, it would help the maintainers keep the history clean

2020-11-04 20:01 UTC, vj-codes commented
@gitpurva hey please solve the merge conflicts, thanks!

2020-11-09 12:17 UTC, closed without merging

2020-11-09 12:32 UTC, devkapilbansal commented
Hi @gitpurva why do you close this pull request. I thought that this pull request is very close to merging

2020-11-09 12:40 UTC, gitpurva commented
Hello @devkapilbansal I have just undo the commits which I have committed(to fix the problem which I encountered by removing one file accidentally) and the pull request got closed automatically . I don't know how!:(  I am new to open source

2020-11-09 15:34 UTC, devkapilbansal commented
Hi @gitpurva this is because there are no changes for which pull request is needed. You just push some changes to this branch and you will get an option to reopen this pull request

2020-12-13 13:02 UTC, devkapilbansal commented
@gitpurva will you please reopen this pull request after making some commits or open a new PR??