fix : Responses does not list 'Notes field is missing.' error message
anitab-org/mentorship-backend pull request #912
Opened 2020-10-15 04:44 UTC by amritada

### Description

Fix issue - Responses does not list "Notes field is missing." error message.

Fixes #613

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Run the app locally and select Mentorship Relation. Go to 'Mentorship relation- send request' and scroll down to the Responses section.  
The error message is showing in the list under HTTPStatus.BAD_REQUEST
![image](https://user-images.githubusercontent.com/42821217/96078082-3d21a400-0e66-11eb-979f-677a8081d61c.png)

### Checklist:

- [ ] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

2020-10-15 19:20 UTC, vj-codes approved these changes, later dismissed
Congrats on your first contribution to the repo @amritada 🎉

2020-10-25 00:11 UTC, isabelcosta requested changes
This looks good @amritada 🤗  You just need to fix the merge conflicts and then I can accept and merge 👏

2020-10-27 18:59 UTC, vj-codes commented
@amritada hey can you please solve the merge conflicts , thanks!

2020-10-28 03:22 UTC, amritada commented
I have resolved the merge conflict. Thanks!

2020-11-13 21:03 UTC, devkapilbansal requested changes
Thanks @amritada for opening this. But I see you have three commits for this single change. Can you please squash your commits into one. Also, please rebase your commit

2020-11-25 22:02 UTC, amritada commented
> Thanks @amritada for opening this. But I see you have three commits for this single change. Can you please squash your commits into one. Also, please rebase your commit

Hi @devkapilbansal , it seems like I messed up my local git history when I did the previous merge because of which I am unable to git rebase and squash. Is it ok if I create a separate clean pull request for this issue and delete this one?

2020-11-29 18:02 UTC, devkapilbansal commented
@amritada you may not need to do so. For eg:- You can do `git reset --hard 60df17f` on this branch in your system to restore the changes done in this pull request.
Or you can trace the changes done here again by fetching upstream and picking this commit like:- 
```
git remote add upstream https://github.com/anitab-org/mentorship-backend.git
git fetch upstream develop
git checkout upstream/develop
git branch -f {your_branch_name}
git cherry-pick 60df17f
```

**Hope it helps**

2020-11-30 02:35 UTC, amritada commented
@devkapilbansal That helped! Thank you so much. I have updated the pull request with a single commit

2020-12-01 00:09 UTC, devkapilbansal approved these changes
LGTM :+1: 

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done or Not Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  
    _Screenshot/gif_:  
![Notes](https://user-images.githubusercontent.com/42766576/100680383-6f944b80-3397-11eb-9a2d-37e4a1053523.png)

    _Expected Result_:  Responses should contain `Notes field is missing`
    _Actual Result_: Same as expected result

3. Status of PR Changed to: Ready to Merge.(as it was approved already before merge conflicts)

2020-12-01 00:10 UTC, devkapilbansal commented
@isabelcosta not asking to change string to f-strings as there is already as issue and WIP Pull request for that

2020-12-01 00:13 UTC, devkapilbansal commented
> @devkapilbansal That helped! Thank you so much. I have updated the pull request with a single commit

Great @amritada 
Also I would recommend you to go through `git` resources once as they will help you a lot.

2020-12-21 19:59 UTC, isabelcosta commented
@devkapilbansal thank you for the review and testing and the comment on f strings. that is ok!

2020-12-21 19:59 UTC, isabelcosta approved these changes
Great work @amritada 👏 
Thank you so much for your contribution!

2020-12-21 20:01 UTC, merged