Bug: Valid Refresh Tokens despite user changing password
anitab-org/mentorship-backend pull request #950
Opened 2020-12-28 17:16 UTC by tichnas

### Description

Fixes # [ISSUE]

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-12-28 17:25 UTC, tichnas commented
@devkapilbansal @isabelcosta As far as I understand, I've to add a test when the password is changed, and we are using the same (old) refresh token (a test where we go inside the if condition). Am I correct? Is there anything else needed?

Thanks in advance :)

2020-12-31 19:07 UTC, devkapilbansal commented
> @devkapilbansal @isabelcosta As far as I understand, I've to add a test when the password is changed, and we are using the same (old) refresh token (a test where we go inside the if condition). Am I correct? Is there anything else needed?
> 
> Thanks in advance :)

Yes @tichnas you have too.

2020-12-31 19:07 UTC, devkapilbansal reviewed
Going in the right direction :+1:

2021-01-02 17:29 UTC, tichnas commented
@isabelcosta @devkapilbansal Please review. Thanks :)

2021-01-02 17:32 UTC, devkapilbansal commented
@tichnas don't use hard coded status codes in test. You have used 401(hard coded). Replace it by using it from HTTP_STATUS as done in API files

2021-01-02 17:34 UTC, tichnas commented
@devkapilbansal It's like this in all test files. Should I change them all or just this one?

2021-01-03 08:04 UTC, devkapilbansal commented
> @devkapilbansal It's like this in all test files. Should I change them all or just this one?

Change for the tests you added. It would be better to open an issue for them

2021-01-04 13:27 UTC, tichnas commented
Thanks for the suggestion @devkapilbansal. I've updated the test case and have also created an issue for all other test cases.

2021-01-04 16:02 UTC, devkapilbansal commented
Thanks @tichnas , although it looks good I will test it soon.
@epidack can you please help in reviewing this pull request?

2021-01-16 18:30 UTC, epicadk approved these changes

2021-01-16 21:57 UTC, devkapilbansal approved these changes
Thanks @tichnas Tested locally and it works

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Refresh Token Validation after Password Change
    _Screenshot/gif_:  
*Refresh Token Valid before Password Change*
![Screenshot from 2021-01-17 03-18-36](https://user-images.githubusercontent.com/42766576/104823887-8291ab00-5873-11eb-9366-2f541af90b83.png)

*Refresh Token invalid after Password Change*
![Screenshot from 2021-01-17 03-21-43](https://user-images.githubusercontent.com/42766576/104823913-b53ba380-5873-11eb-8bb2-b00a8a248f2d.png)

    _Expected Result_:  Token should be invalid after password change
    _Actual Result_: Same as expected
    
3. Status of PR Changed to: Ready to Merge.

2021-01-16 21:58 UTC, devkapilbansal commented
@vj-codes @isabelcosta Kindly review this PR

2021-01-17 08:52 UTC, vj-codes approved these changes
Thank you for your contibution @tichnas 🎉

2021-01-17 08:53 UTC, vj-codes commented
Adding label ready to merge since testing is done above

2021-01-20 23:54 UTC, isabelcosta commented
@tichnas @devkapilbansal and @vj-codes I put the "on Hold" label because I am not sure this is a secure solution, to include the password hash in the token. This is because a jwt token, when decoded can reveal the content of the identity. You can see here https://jwt.io/ the composition of a token. I would like to have other opinions on this, perhaps we could reach out to Zulip community and ask. I'll post on Zulip and look more into this.

cc @ramitsawhney27 @m-murad in case you have any idea about this 🙏

2021-01-21 14:37 UTC, epicadk commented
> @tichnas @devkapilbansal and @vj-codes I put the "on Hold" label because I am not sure this is a secure solution, to include the password hash in the token. This is because a jwt token, when decoded can reveal the content of the identity. You can see here https://jwt.io/ the composition of a token. I would like to have other opinions on this, perhaps we could reach out to Zulip community and ask. I'll post on Zulip and look more into this.
> 
> cc @ramitsawhney27 @m-murad @SanketDG in case you have any idea about this 🙏

uh oh! 😅 I see it now. This was not what I meant. The content of the token need not be changed. What needs to be changed is the refresh signing key. Thanks @isabelcosta for catching this.

2021-01-21 14:39 UTC, epicadk requested changes
The contents of the token do not need to be modified. Just append the users password hash while you sign the refresh token that is all.

2021-01-24 01:03 UTC, mtreacy002 commented
Hi @isabelcosta, @tichnas, @devkapilbansal, @epicadk, and @vj-codes. Just thought I might share my two cents [here](https://anitab-org.zulipchat.com/#narrow/stream/212722-general/topic/Advice.20Needed/near/223787574) 😉. Apologies if it doesn't make sense though, still a newbie here with python and jwt 🤣🤣🤣.

2021-02-09 20:05 UTC, isabelcosta commented
I will close this PR due to inactivity. Thank you @tichnas for your contribution 🙌

2021-02-09 20:05 UTC, closed without merging