test : Refactor hard-coded status codes to HTTPstatus in tests
anitab-org/mentorship-backend pull request #982
Opened 2021-01-21 14:24 UTC by cypherean

### Description

Refactored `tests/task_comments/` and changed hard-coded status codes to respective HTTPstatus.

Fixes # [ISSUE]

### Type of Change: test

### How Has This Been Tested?

![Screenshot from 2021-01-21 19-37-32](https://user-images.githubusercontent.com/66686803/105363423-035cf800-5c22-11eb-9c6c-dc50bc35fe63.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

2021-01-23 12:54 UTC, vj-codes requested changes
@cypherean hey please change the code as mentioned in the suggested changes in every file of the PR . Just these small changes and you are done:)

2021-01-23 12:54 UTC, vj-codes commented on tests/task_comments/test_api_create_task_comment.py
> +        self.assertEqual(HTTPStatus.BAD_REQUEST, actual_response.status_code)
```suggestion
        self.assertEqual(HTTPStatus.BAD_REQUEST.value, actual_response.status_code)
```

2021-01-23 12:54 UTC, vj-codes commented on tests/task_comments/test_api_create_task_comment.py
> +        self.assertEqual(HTTPStatus.BAD_REQUEST, actual_response.status_code)
```suggestion
        self.assertEqual(HTTPStatus.BAD_REQUEST.value, actual_response.status_code)
```

2021-01-23 13:16 UTC, cypherean commented
Made the required changes @vj-codes :smile:

2021-01-25 01:33 UTC, vj-codes commented
@cypherean hey great work on updating the changes!
Although I still see some places where` .value` isn't added , this will not produce the expected output so please add it in those places as well.

2021-01-26 09:23 UTC, Aaishpra requested changes
Hi @cypherean can you run black tests/folder_name_here/file_name_here.py for all the files or black . so that the code will be reformatted according to black tool standards and the failing check will pass.

2021-01-26 20:12 UTC, vj-codes approved these changes
LGTM 🎉 
Thank you for your contribution @cypherean

2021-01-26 20:13 UTC, vj-codes commented
@Aaishpra hey can you review this once more?

2021-01-27 03:42 UTC, Aaishpra approved these changes
Thanks for the quick change @cypherean great work.

2021-01-28 10:18 UTC, chinmaym07 approved these changes
LGTM :+1:
Thanks @cypherean for your contribution

Tested locally and verified that all hard coded response values are replaced

The changes made in this PR were tested locally. Following are the results:

1) Code review - Done

2) All possible responses (positive and negative tests) were tested as below:

     - Test1 Description Replaced hard coded responses in mentioned files
    - Expected Result: tests/task_comments files should not contain hard coded responses

 3) Additional Comments: Run `python -m unittest discover tests to ensure all tests passed

2021-01-28 17:44 UTC, epicadk commented
> LGTM 👍
> Thanks @cypherean for your contribution
> 
> Tested locally and verified that all hard coded response values are replaced
> 
> The changes made in this PR were tested locally. Following are the results:
> 
> 1. Code review - Done
> 2. All possible responses (positive and negative tests) were tested as below:
>    
>    * Test1 Description Replaced hard coded responses in mentioned files
>    * Expected Result: tests/task_comments files should not contain hard coded responses
> 3. Additional Comments: Run `python -m unittest discover tests to ensure all tests passed

Can you add a screenshot of the tests?

2021-01-29 01:03 UTC, merged

2021-01-29 01:04 UTC, isabelcosta commented
@epicadk thank you for asking for more clarifications 🤗 I merged, since the PR check was passing and these were changes made to the tests module only.
Thank you all for reviewing this 👏